### ISSUE TITLE
imgview does not open sxiv on the image that was hovered

### ISSUE THREAD

**Issue by tonijarjour** [jarun/nnn#1083]
https://youtu.be/mDO9ks_D4OI

The first image I open is what should come up when using imgview. But as you can see, a different image comes up.

**Comment by jarun** [comment]
@luukvbaal I was checking the `imgview` code. Why are we creating the `.nthumbs` directory and calling `view_files` when the hovered entry is a file?

**Comment by jarun** [comment]
The question is for `sxiv`.

**Comment by luukvbaal** [comment]
To be consistent in showing thumbnails for media files regardless of whether  file or a directory is hovered. Could be changed if not desired but since we merged the thumbnail plugin and you did not want to lose functionality this seemed to make the most sense to me.

#1084 should restore opening the hovered image functionality that was lost in the merge.

**Comment by jarun** [comment]
Done!

**Comment by jarun** [comment]
Added a note in the review. Please check.
