### ISSUE TITLE
Documentation issue: what is `NNN_FIFO` supposed to point to?

### ISSUE THREAD

**Issue by galou** [jarun/nnn#1089]
**Is your feature request related to a problem? Please describe.**

This is a documentation issue. The [Chapter "Set up NNN_FIFO"](https://github.com/jarun/nnn/wiki/Live-previews#set-up-nnn_fifo) doesn't state what `NNN_INFO` is supposed to point to. Is it a configuration file, is it a directory with executables? From the directory from where I ran `make` I tried `./nnn -a $(pwd)/plugins` but I dont' see any preview. There are chances that I miss something else but anyway, I think that the documentation should be more specific.

**Describe the solution you'd like**

Explain `NNN_INFO` in the documentation.

**Additional context**

Newbie here.

**Comment by KlzXS** [comment]
FIFOs are [named first-in-first-out pipes](https://www.gnu.org/software/libc/manual/html_node/Pipes-and-FIFOs.html). It's a way for two processes to communicate. The manpage mentions it in passing. It also meantions that `-a` doesn't take a path. What you provided is taken as the starting path.

The preview doesn't start automatically. It's a plugin, must be assigned a plugin key and launched with it to start working or you can use `-P <key>` to invoke it at startup as the wiki states. See the plugin itself for more details.

**Comment by KlzXS** [comment]
I don't think the documentation is lacking. Everything can be found and pieced together between the wiki, manpages and plugin scripts themselves. All of which you should read in general not just for `nnn`.

Wikis to find out how to use a program, manpages to find out how to invoke it from command line, what flags it accepts, etc. And plugins scripts simply because it is strongly recommended to at least glance over a random script downloaded from the internet that you are about to run.

FIFOs are not unique to `nnn` or any other project and are used all over. It is beyond the scope of our documentation to describe what they are and how to create them. It is assumed that you that you come with some pre-existing knowledge of how linux works. That is for someone else to explain and they could do a better job.

Hope this clears it up.
