### ISSUE TITLE
x and S option not working in combination

### ISSUE THREAD

**Issue by Randalix** [jarun/nnn#1092]
- [x] Operating System: Debian bullseye
- [x] Desktop Environment: dwm
- [x] Terminal Emulator: st
- [x] Shell: bash
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: x S
- [x] Configuration options set: NNN_TRASH NNN_USE_EDITOR NNN_FCOLORS='c1e2272e006033f7c6d6abc4'

- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
$ nnn -S -x
selection to clipboard not working.
running only nnn -x selection to clipboard works as expected

**Comment by jarun** [comment]
The reason is the first time you ran with `-S` you didn't include `-x`.
So the original option is stored in the session data as you wanted it. whenever you load the session at startup, your passed option is overwritten. And that's correct by the definition of session.

You can deleted the stored `@` session and start afresh with `-x` option passed.
