### ISSUE TITLE
preview-tui with kitty+tmux no longer works.

### ISSUE THREAD

**Issue by greenfoo** [jarun/nnn#1093]
**Problem description**
If I run nnn inside tmux inside kitty and try to use the "preview-tui" pluging, I get this error:

```
$KITTY_LISTEN_ON not set!
Please read Usage in preview-tui.
```

This did not happen before.

**Possible solution**
In commit d99894311941498b9bf93c9f3ff9b55a533ed6cf this change was made:

![image](https://user-images.githubusercontent.com/42691086/124458296-16592400-dd8d-11eb-80f7-5c64b71aa0be.png)

The thing is that, because of the new condition inside the red rectangle, I can no longer use the preview-tui plugin when using tmux inside kitty (when I do, the error a few lines below is shown and "togglepreview" is never called).

The reason is that KITTY_WINDOW_ID is defined inside tmux.

What I did is to change the original line:
```
elif [ "$KITTY_WINDOW_ID" ] && [ -z "$KITTY_LISTEN_ON" ]; then
```
...into this:
```
elif [ "$KITTY_WINDOW_ID" ] && [ -z "$KITTY_LISTEN_ON" ] && [ -z "$TMUX" ]; then
```

Would this be an acceptable solution?

Thanks.

**Comment by luukvbaal** [comment]
I suppose the change is fine although I'm not sure why you would use tmux inside kitty terminal which already provides multiplexing.

**Comment by luukvbaal** [comment]
Also not sure the possibility to use `tmux` inside `kitty` for `preview-tui` is obvious from the current documentation.

If you say it works fine and has merit perhaps we should fix that.

**Comment by Kabouik** [comment]
To bring grist to the mill, I do use `tmux` inside `kitty` occasionally too, because `kitty` is my `TERMINAL` and with `tmux` I can easily restore complex sessions with multiple panes and tabs pre-configured, and because sometimes I need `tmux` not only for multiplexing but also for accessing sessions across different machines. 

I am not using the latest version of `nnn` and `preview-tui` (my plugins still are in a version where `preview-tui` and `preview-tui-ext` are two different things), but `preview-tui` works in `tmux` within `kitty` on my end.

**Comment by greenfoo** [comment]
Thanks.

PS: My use case is similar to Kabouik's: I use kitty **locally** (it's my default shell) to SSH into a machine where I start a **remote** tmux session I can restore at any point.
