### ISSUE TITLE
Defect to track persistent selection issues

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#1104]
Seeing the following issues with new persistent selection implementation:

Env:

- My start dir is `nnn` directory
- I have 1662 files in `/usr/bin`

#### Issue 1

1. Go to `plugins` dir and select some files with <kbd>^J</kbd>
2. Go to `/usr/bin` dir and select some files with <kbd>^J</kbd>
3. Press <kbd>a</kbd>
4. Press <kbd>A</kbd>
5. Press <kbd>y</kbd> to continue
6. Go to parent `/usr`
7. Go back to `/usr/bin`

Observation: all files are selected.

#### Issue 2

1. Go to `plugins` dir and select a file with <kbd>^J</kbd>
2. Go to `/usr/bin` dir and select the first file with <kbd>^J</kbd>
3. Go back to `nnn` dir with <kbd>@</kbd>
4. Go back to `/usr/bin` dir with <kbd>-</kbd>
5. Go to the end of the dir and select the last file with <kbd>^J</kbd>
6. Press <kbd>a</kbd>
7. Press <kbd>A</kbd>
8. Press <kbd>y</kbd> to continue

Observation: `nnn` quits.

@KlzXS please take a look.

**Comment by pvx-** [comment]
The problem seems to be that after clearing/shrinking selection the space (memory buffer) after is still "active" (searched), simplest example I found:

1. Select first 2 files in any directory
2. `m` `m` to clear the selection
3. Select first file in the directory again
4. Change dir/context and come back - both files are selected again (the selection file correctly contains only the first one)

**Comment by jarun** [comment]
Maybe lacking a NUL-terminator or the selection buffer length not updated correctly.

**Comment by KlzXS** [comment]
Used the wrong selbuf length. Check the PR.
