### ISSUE TITLE
What does "no unconfirmed user data collection" mean?

### ISSUE THREAD

**Issue by kaushalyap** [jarun/nnn#1109]
What does "no unconfirmed user data collection" mean in the ReadMe?

Does nnn have an option to collect usage statistics or something?

**Comment by jarun** [comment]
The only data stored is the config option and runtime paths, files etc. Those are already user-confirmed. No other data is used.

**Comment by 0xACE** [comment]
> What does "no unconfirmed user data collection" mean in the ReadMe?

I guess "no unconfirmed user data collection" refers to the case where you provide your own plugin that sends your data to 3rd parties, e.g.:
If you have a plugin that uploads images to _imgur_, `nnn` would be in no control of what _imgur_ collects from the metadata of your transfer. This is solely your own responsibility as a end user, use services that respect your privacy as per your wishes.

What is important is that `nnn` itself **does not collect any user data of any sort**

> Does nnn have an option to collect usage statistics or something?

`nnn` does not collect any data at all

I only responded to clarify, because it seemed like you had concerns of another "audacity fiasco" / "privacy invasion" situation...
