### ISSUE TITLE
cd on quit not working MacOS Mojave 10.14/ZSH

### ISSUE THREAD

**Issue by weatherbell** [jarun/nnn#118]
Using Python 3.7
Doesn't work in bash either.
[quitcd.mp4.zip](https://github.com/jarun/nnn/files/2496502/quitcd.mp4.zip)

Looks cool otherwise - good job 👍

**Comment by jarun** [comment]
Did you follow the instructions [here](https://github.com/jarun/nnn#cd-on-quit) for your shell (zsh/bash)?

**Comment by jarun** [comment]
I believe it's an env issue as we have users who are using `nnn` on OS X. Please feel free to revert if you have any additional info.

**Comment by jessemillar** [comment]
I am pressing uppercase `Q` and have `export NNN_TMPFILE="/tmp/nnn"` exported and still cannot `cd` on close. I'm on macOS 10.13.6 using ZSH.

**Comment by zmwangx** [comment]
```zsh
setopt xtrace; n; unsetopt xtrace
```

**Comment by jessemillar** [comment]
@zmwangx Am I meant to run that in my terminal? This is the output (which probably isn't helpful):
```
~ > setopt xtrace; nnn; unsetopt xtrace                                                                130
+-zsh:1> nnn
+-zsh:1> unsetopt xtrace
```

**Comment by zmwangx** [comment]
Of course, running a command wouldn't cd you anywhere. You need to source the tempfile generated by the command (somewhat questionable if you ask me, but if you want the feature then that's what you have to do), which means using a wrapper function like https://github.com/jarun/nnn/blob/master/scripts/quitcd/quitcd.zsh/.

Please actually read the docs [1] rather than just the title of a feature...

[1] https://github.com/jarun/nnn#cd-on-quit
