### ISSUE TITLE
Ranger-like workspaces

### ISSUE THREAD

**Issue by lenormf** [jarun/nnn#124]
Hi,

Is there's any way to implement `ranger` workspaces? I think I could use bookmarks, but I don't see in the documentation how to use them, and then I would need some kind of visual sign of which bookmarked directory I'm under.

Thanks.

**Comment by jarun** [comment]
> Is there's any way to implement ranger workspaces?

I don't use ranger and `nnn` doesn't follow it either. You have to explain more.

> I don't see in the documentation how to use them

It's the first item in How To list: https://github.com/jarun/nnn#add-bookmarks

> I would need some kind of visual sign of which bookmarked directory I'm under.

`nnn` shows the directory you are under all the the time. To see configured bookmarks, press `?`.

**Comment by lenormf** [comment]
![](https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fmalkalech.com%2Fwp%2Fwp-content%2Fuploads%2F2017%2F01%2Franger_filer_ss_colorscheme3_snow.png&f=1)

Workspaces are the numbers in the top-right corner, upon hitting <kbd>alt</kbd>+<kbd>[0-9]</kbd>, a new workspace in the current working directory is being opened if the target workspace doesn't exist already, otherwise the already existing workspace is switched to.

They allow multiplexing (without having to use something like `tmux`), have visual feedback (the workspace numbers are highlighted), and can be removed easily.

**Comment by jarun** [comment]
OK, so it's similar to the multi-tab feature in file managers. `nnn` does not have multi-tab or multi-pane. The reason is there already are several solutions like terminator/tilix/AltYo/byobu/GNU screen (other than tmux which you mentioned). And you can always open a bookmark directly using the key in a new instance on `nnn`:

    nnn -b dw // say the key to your Downloads directory is 'dw'

From your description it seems for you the important factor is storing the contexts of your work. That is ensured by terminal emulators (in addition to multiplexers) with drop-down mode and not the file manager (other than those which store user information to disk across sessions). Incidentally, there are no modern terminal emulators which support drop-down mode but not multi-tab or multi-pane.

Personally I use terminator in drop-down mode because it supports vertical splits and tabs (I fire an instance of `nnn` in each pane when required) which deliver the _workspace_ experience of ranger.

**Comment by lenormf** [comment]
I want to be able to explore different directories with the same `nnn` process, since I usually spawn it in a single `tmux` pane and don't have anymore space for more.

**Comment by jarun** [comment]
> since I usually spawn it in a single tmux pane and don't have anymore space for more.

In your earlier comment you mentioned _without having to use something like `tmux`_ so I ruled out tmux and here you mention you use tmux. Both are contradictory.

If you don't have space for an extra pane AND you would like to use `nnn` use a terminal emulator that supports `tabs`. That way you don't have to use up extra space. From what I understand it's the same experience as ranger.

> I want to be able to explore different directories with the same nnn process

As I mentioned earlier, `nnn` does not have this feature of multi-tab.

**Comment by lenormf** [comment]
I want a single process to handle several directories without having to use an external multiplexing mechanism.

I spawn my file explorer in a single `tmux` pane, and am not interested in "tabs" or spawning more panes/windows.

**Comment by jarun** [comment]
> and am not interested in "tabs" or spawning more panes/windows.

then it's pretty established `nnn` is not the right utility for you. it's all there in the documentation which you should have read first. the documentation is there for a reason.
