### ISSUE TITLE
`nnn` causes freezes while trying to preview a GIF

### ISSUE THREAD

**Issue by UtkarshVerma** [jarun/nnn#1264]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Void Linux
- [x] Desktop Environment: None (dwm)
- [x] Terminal Emulator: st
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable): None
- [x] Program options used: -e -P p (preview-tui)
- [ ] Configuration options set:
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
- Try to preview a GIF recorded by [Peek](https://github.com/phw/peek).
- PC freezes at this point with RAM usage suddenly increasing by 3GB. (definitely something in /tmp/nnn/previews/)

Here is a sample GIF recorded by Peek:
https://user-images.githubusercontent.com/31820255/146667479-2c573ce1-80c9-4825-8d71-7e863235b14b.gif

**Comment by luukvbaal** [comment]
This is just a limitation of the convert command used to extract the frames from the gif.  For me it core dumps when trying to run `convert -coalesce` on that file. 

It is probably too high of a framerate. Not sure if we can use some ImageMagick flags to limit the framerate.

**Comment by luukvbaal** [comment]
Explicitly setting `MAGICK_TMPDIR` to `/tmp` avoids the coredump for me on your gif. I'll make a PR that falls back to converting when RAM fails.

Keep in mind that this can be very slow on the affected gifs. At least you will have working previews once the gif has been converted.

**Comment by luukvbaal** [comment]
@UtkarshVerma please check if https://github.com/jarun/nnn/pull/1267 fixes the issue. You might have to first manually delete the gifs cache folder if it is empty(it will skip converting if the folder already exists).

We could also delete the empty folder in the script if conversion fails. That would however result in us trying to convert the gif each time it is hovered and we know it will fail since the folder is empty so I opted not to do that.
