### ISSUE TITLE
tried to mass rm files, error

### ISSUE THREAD

**Issue by ongspxm** [jarun/nnn#130]
I first `^Y`, then `<space>` to select all my files. Then i tried to `X`, there was a slight flash in the screen, showing some `rm missing operand` error.

I tried to trace the raw command to this:
https://github.com/jarun/nnn/blob/b6942c384d38cbfa4f44d0f56a5073be25256670/src/nnn.c#L3055

I check my rm supports both `I` and `r` flag. Any help pls?

**Comment by jarun** [comment]
What is your distro? I am on Ubuntu 18.04 amd64 and I've been using this for a few days (since I wrote it) without any issues.

It would be great if you can tinker around for a while and figure it out. A patch would be highly appreciated.

To begin with you can remove the params one by one and see which one gives a clean result.

**Comment by jarun** [comment]
Ahh OK! The problem is you have to mark the selection end. So the sequence to select multiple files is:

- `^Y`
- mark files using `space` or `^K`
- press `^Y` to end selection

from your description it seems like you have missed the second `^Y`.

**Comment by ongspxm** [comment]
oh, works, thanks

**Comment by jarun** [comment]
I have updated the docs at commit 5dea6504365367d254650e3cafb67f5813223505 to make this more clear.
