### ISSUE TITLE
File selector mode

### ISSUE THREAD

**Issue by mzanibelli** [jarun/nnn#133]
Hi,

I wonder if there would be a way to tell `nnn` to print the path of the selected file on standard output and exit instead of triggering `xdg-open` or `$EDITOR` by default. I've been trying to hack it with something like `NNN_USE_EDITOR=1 VISUAL=echo nnn` but it obviously doesn't work very well as the program doesn't exit afterwards.

I'd love to be able to communicate with let's say Vim and use `nnn` as a file chooser leveraging the new `:terminal` feature. I currently use `ranger` which has a `--choosefile` option but it's very slow and I don't need so many features.
Scripts could be a way to do that but it doesn't run by default on Enter.  Any ideas based on clever environment variables use? If not, could you please consider adding this? I'd try but my understanding of C probably isn't good enough. 

Nice work by the way!

**Comment by mzanibelli** [comment]
Closing as I apparently can't read a homepage correctly. See https://github.com/jarun/nnn/issues/110#issuecomment-441264931.

**Comment by jarun** [comment]
@mzanibelli This is interesting! I wasn't aware of the `:terminal` command. I will see what I can do.

However, I don't see much difference between the workflow you mentioned and the following (where `nnn` initiates the workflow instead of `vim`):

- run `nnn`
- navigate to a file and open it using `vim` (`NNN_USE_EDITOR` should be set with `EDITOR` set to `vim`)
- edit and close the file
- navigate to another file and open it with `nnn`
...

what difference do you see? (I'm sure I am missing something here.)

**Comment by jarun** [comment]
Response from @mzanibelli:

Well, apart from my habit of starting my day with `vim` and ending it with `:quit`, the benefits I can think of are:

* the ability to choose from Vim which file selector to use (the `fzf` fuzzy finder works exactly the way I'm talking about, so it's a matter of replacing the name of the binary in the corresponding VimL code)

* starting Vim in the project root, and stay there, but mapping a key to somthing like `:terminal nnn %:h` to quickly navigate between files in the folder of the one being currently edited

* integrate with a lot more tools and scripts

* another one I forgot to mention but often use: having a Vim split with the code and another one with a file manager, quickly move between files and fire `$PAGER`through the file manager while keeping visual context

**Comment by jarun** [comment]
> in the corresponding VimL code

Can you please share this? I need to understand what it is.

I have written a quick patch which we can extend to multiple files here: https://github.com/jarun/nnn/tree/nnn_print

See if it's the thing you need.

Also, I found a vim plugin here: https://github.com/ranger/ranger/blob/master/examples/vim_file_chooser.vim
which reads in the file names from a temp file. Are you referring to this script?

**Comment by jarun** [comment]
Little more detail on the patch:

The patch writes the selected file name to `stdout`.

Now, if you are referring to the vim plugin then it's _absolutely easy_ to implement it with `nnn`. We write selection names to a file `.nnncp`. Currently we remove the file when `nnn` exits. We can provide a hook to keep even after `nnn` quits and the plugin can simply read the file in.

**Comment by jarun** [comment]
@mzanibelli Yes, on closer inspection, I think we are discussing the same script. So I can throw in a new option that takes in a custom `.nnncp` file and _doesn't remove_ the file on exit. So you just select a file (or multiple files) and exit `nnn` to get the list and do whatever you want with it.

Sounds good?

**Comment by jarun** [comment]
Response from @mzanibelli:

My VimL code for reference: https://github.com/mzanibelli/dotvim/blob/6dd7012a973bbc7711070dbb2f9487a87f5b485e/autoload/edit.vim#L10
Goal: replace l11 with `nnn`

We're getting there! I was not aware of `.nnncp` which seems even closer to what `ranger` does with `--choosefile`. Quick thoughts:

* `stdout` is better because it is, in my opinion, the way to go in any *nix environment

* I see that the only required code was to use `mkpath()` before printing so I think I can do exactly what I want now, I'll try to submit a patch

* bonus: print path and quit on`→, ↵, l, ^M` when using this feature (only files, not folders)

* mutiple file selection would be nice indeed!

**Comment by jarun** [comment]
> `stdout` is better because it is, in my opinion, the way to go in any *nix environment

See my last comment. In that case, we can have the option such that, if no filepath is provided, `nnn` writes the selection list to `stdout` before exit.

**Comment by mzanibelli** [comment]
Side note, I patched the program to avoid forking before the `exec()` call in `spawn()`, and `NNN_USE_EDITOR=1 EDITOR=echo VISUAL=echo ./nnn` does exactly what I want when pressing Enter. That's another way to approach the problem... Is that even _allowed_? :smile:

**Comment by jarun** [comment]
I am working on using a custom `.nnncp`. Please hold on.

**Comment by mzanibelli** [comment]
Your next couple of drinks is on me, kind stranger. I'll hold on from now.

**Comment by jarun** [comment]
Thanks! That's very kind of you. :+1:

**Comment by jarun** [comment]
Try https://github.com/jarun/nnn/commit/9e974be3ddb42fd0b00d12b82610f5828fd2fd3a (on master this time). The option is `-p`.

To _pick_ selection to a file:

    nnn -p ~/dir/file

To print to stdout:

    nnn -p -

Please let me know how it goes.

**Comment by jarun** [comment]
@mzanibelli I have added a modified version of the plugin here: https://github.com/jarun/nnn#work-faster-at-rename-prompt

Currently it opens nnn in the directory where vim was opened. Can you please add an option (setting + keybind (Leader N) + command (:NP)) so it can be opened in the directory of the currently opened file?

I must admit my knowledge of vimL is limited. In fact this is the first time I am tinkering with it.
