### ISSUE TITLE
image preview not work in preview-tui

### ISSUE THREAD

**Issue by lythesia** [jarun/nnn#1405]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: MacOS Monterey
- [ ] Desktop Environment:
- [x] Terminal Emulator: iterm2
- [x] Shell: fish
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: adr
- [ ] Configuration options set:
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

nnn installed by homebrew
plugins enabled: `p:preview-tui;z:autojump;v:imgview`, and `viu` installed as image viewer

#### Exact steps to reproduce the issue

* toggle preview-tui mode and move selection to some image and no preview generated
* `;v` on image did not show image in terminal (instead it looks like invoke `open` not `viu`, and image file opened in mac's preview.app, but manually exec `viu -t` works fine in iterm2)
* `ps` shows no `viu` process
* enable `DEBUG_LOG=1` but no log files in /tmp, no temp image files neither

**Comment by jarun** [comment]
> `;v` on image did not show image in terminal

You should press `;p`.

Also, do you have tmux (>=v3.0) installed?

**Comment by luukvbaal** [comment]
> * `;v` on image did not show image in terminal (instead it looks like invoke `open` not `viu`, and image file opened in mac's preview.app, but manually exec `viu -t` works fine in iterm2)

This seems to be the intended behaviour, looking at `imgview` source: https://github.com/jarun/nnn/blob/6c197f5f024c9d726de145a19c3fcd66fdb365d1/plugins/imgview#L74

I don't know why. Removing that if clause should get you `viu` previews with it installed.

Tmux is not required when using iterm2 and indeed not recommended since https://github.com/jarun/nnn/commit/e20cfd67a1c3de635a1f562420bfe15e37296dd9. I think it might even screw things up as it takes tmux takes precedence over iterm looking at `preview-tui` source. Perhaps we should swap them around. Are you using tmux @lythesia?

**Comment by lythesia** [comment]
> > `;v` on image did not show image in terminal
> 
> You should press `;p`.
> 
> Also, do you have tmux (>=v3.0) installed?

yeah, I know, `;p` to toggle preview-tui, I use `;v`to check wether imgview plugin works too, but it turns out neither of them works
tmux version: tmux 3.2a

**Comment by lythesia** [comment]
> > * `;v` on image did not show image in terminal (instead it looks like invoke `open` not `viu`, and image file opened in mac's preview.app, but manually exec `viu -t` works fine in iterm2)
> 
> This seems to be the intended behaviour, looking at `imgview` source:
> 
> https://github.com/jarun/nnn/blob/6c197f5f024c9d726de145a19c3fcd66fdb365d1/plugins/imgview#L74
> 
> I don't know why. Removing that if clause should get you `viu` previews with it installed.
> 
> Tmux is not required when using iterm2 and indeed not recommended since [e20cfd6](https://github.com/jarun/nnn/commit/e20cfd67a1c3de635a1f562420bfe15e37296dd9). I think it might even screw things up as it takes tmux takes precedence over iterm looking at `preview-tui` source. Perhaps we should swap them around. Are you using tmux @lythesia?

Thanks for pointing out why imgview not work, I did not check the source thoroughly
At first I was only using iterm2, and I also tried with tmux, and no luck

**Comment by mobi35** [comment]
I got the same problem.. image is not showing in preview-tui. did you manage to solve it @lythesia ??

**Comment by lythesia** [comment]
@mobi35 nope

**Comment by luukvbaal** [comment]
I revived my macOS virtual machine and image preview works as expected with the latest version of preview-tui and
```sh
brew install nnn
brew install viu
brew install iterm2
```

I don't know what else to tell you.

**Comment by lythesia** [comment]
@luukvbaal I tried your steps and it works now! Though I still don't know why, maybe some env's messed up at that point. Thanks!

**Comment by mobi35** [comment]
> 

I'm using kitty as my terminal.

**Comment by luukvbaal** [comment]
On macos? Have you installed the necessary dependencies?
https://github.com/jarun/nnn/blob/89bd541562e7c9da395a8e919939e7f480d03a2c/plugins/preview-tui#L67-L72

**Comment by mobi35** [comment]
> 

I have to install ImageMagick, it's working now..  How do you zoom image?

![image](https://user-images.githubusercontent.com/16623700/176158003-8eafd840-5a09-4cb6-9ecf-f76a3fdc2e6e.png)

**Comment by luukvbaal** [comment]
You open it in your image viewer, preview-tui is for previews only... 

Although the image does not seem to fit to the available space, we do do that for ueberzug. If that's what you mean there do seem to be some [options](https://sw.kovidgoyal.net/kitty/kittens/icat/) available to achieve that. Perhaps we should include those but I don't use kitty myself and since it was never brought up perhaps it is not to stretch the image?
