### ISSUE TITLE
Are multiple keys for plugins absolutely necessary?

### ISSUE THREAD

**Issue by indeedwatson** [jarun/nnn#1470]
I make minimal use of plugins, I'd really like to just bind a plugin to a single key, not having to precede it by `;`.

Additionally, the preview script should work by default on hovered files. I really like the swiftness of the workflow with nnn, and having to press multiple keys to enable plugins, just because they're plugins, seems arbitrary and contrary to the flow that nnn permits with its default features.

**Comment by N-R-K** [comment]
You can use <kbd>Alt+key</kbd> to run a plugin (that's been assigned to "key") as well.

**Comment by indeedwatson** [comment]
I tried that unsuccessfully, probably did it wrong, but in any case I really do mean a single key.

The idea is that the user should not have to distinguish if an action is triggered by a plugin or if it's a default feature, I want to do X action > I bind it to Y key (or any combination of keys, but the user should have the choice).

I understand that there might be some reason in the code to rely on key combinations, but from a UX perspective, I can't see why.

**Comment by N-R-K** [comment]
> I tried that unsuccessfully, probably did it wrong

Due to how terminals work, certain keybindings might send another key (see [this comment for example](https://github.com/jarun/nnn/issues/1416#issuecomment-1178010147)). This is out of `nnn`'s control.

- - -

> The idea is that the user should not have to distinguish if an action is triggered by a plugin or if it's a default feature, I want to do X action > I bind it to Y key (or any combination of keys, but the user should have the choice).

The only way to customize keybindings right now is to edit `nnn.h` and compile manually. The topic of custom keybinding support came up a good ton of times, and was turned down. I doubt that stance has changed, so closing this issue.

**Comment by indeedwatson** [comment]
Was there any reason provided that would make sense from a user perspective?

I'm really enjoying the workflow of nnn so far, but if the mindset is "code first, user experience second" I would be nice to know before I get more acostumed to it.

**Comment by N-R-K** [comment]
Because `nnn`, similar to various [suckless](suckless.org) projects, doesn't use any config files. Adding a config file would:

0. Slow down startup.
1. Add lots of more code if we want to parse things ourselves or additional third party library dependency.

> but if the mindset is "code first, user experience second"

The speed/performance of `nnn` is part of the user experience ;)
And it's something which I personally appreciate and something that many other application don't even offer/care about.

But if *really* want __runtime__ customizable keybindings then there's plenty of other terminal file-managers available. Try to pick one that offers it.

**Comment by indeedwatson** [comment]
> The speed/performance of nnn is part of the user experience ;)

Yeah, which is why it is counter intuitive to me that I'd have to press two buttons, which is slower. The bottleneck in speed is very often the user processing what they have to do, not whether the program takes 0.1 or 0.12ms.

I was afraid this was close to the suckless philosophy, which prioritizes code over user experience, and like many philosophies, in practice it ends up contradicting itself.

Thanks for the responses, I think I'll give lf a try.
