### ISSUE TITLE
Specify config directory

### ISSUE THREAD

**Issue by acamso** [jarun/nnn#1472]
Hi, I am currently setting up `nnn` and see the config directory defaults to `XDG_CONFIG_DIR` and `~/.config`. I personally prefer a different directory specified through an env variable. I realize this is an unpopular preference, but figured I'd post it for consideration as others may prefer an options as well. In the meantime, a soft-link works. Cheers

**Comment by N-R-K** [comment]
> I personally prefer a different directory specified through an env variable.

You can set `XDG_CONFIG_HOME` to something else. The entire point of xdg spec was to allow users to control their config dir instead of every application polluting `$HOME` with dotfiles.

And if you want to change the config dir *just* for `nnn` without changing `$XDG_CONFIG_HOME` globally, you can use the following:

```console
$ XDG_CONFIG_HOME="/custom/path/" nnn
```

You can turn this into an alias or a function in your shell rc as well.

**Comment by acamso** [comment]
Hi sir - not everyone follows the XDG spec. Flexibility is always nice for directory locations. With that being said, an alias works for now. Thanks.
