### ISSUE TITLE
Colemak users should compile with colemak patch, not use stale Gitlab fork

### ISSUE THREAD

**Issue by jacmoe** [jarun/nnn#1584]
#### Environment details (Put `x` in the checkbox along with the information)

- [x ] Keyboard Variant: Colemak
- [x ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. Discover *nnn*
2. Navigate to Github repository
3. Read the Wiki, and see that Colemak users should use Queer Bird's `nnn-colemak` on Gitlab

The problem, of course, is that we should instead compile *nnn* from source, with the `colemak` patch. Much better!

I guess not every colemak using *nnn* convert is as observant as I was, so perhaps the wiki could be fixed with a note that colemak users might want to compile from source with the colemak patch.

Thanks for *nnn*! :heart: 

EDIT: I would normally just have issued a PR, but I am not sure what to edit.
Maybe saying something like we should do a `make O_COLEMAK=1`

**Comment by jacmoe** [comment]
That sounds great, thanks!
I applied the patch and I find it very useful, but it would of course be better if I didn't have to reach down for M because H and M is swapped. That's truly minor!
I would be even happier if @luukvbaal would be so kind to update the patch for people who don't use colemak-dh.

**Comment by luukvbaal** [comment]
I really would rather someone invested in the patch would step up to submitting/maintaining a patch they're interested in, that was the idea of the user-patch framework. I can't speak to the quality of these keymap patches(the current colemak patch was not written by me nor do I use it, I just added it to the framework).

But yeah as I understand it there are two colemak variants. I guess since we already have a keymap patch in the framework others are welcome too. 

> EDIT: I would normally just have issued a PR, but I am not sure what to edit.
Maybe saying something like we should do a make O_COLEMAK=1

I think in this case a PR would indeed replace the current colemak patch with a (regular?) colemak patch and move the current patch to `patches/colemak-dh` and add a `O_COLEMAK-DH` make variable.

**Comment by jacmoe** [comment]
OK, here's how I suggest that this is done:

1. Someone else renames the patch and update the wiki/makefile with new O_COLEMAK_DH flag
2. I learn how to export a diff.
3. I experiment with a good colemak patch.
4. After having used `nnn` for a month with the patch applied, and the kinks ironed out, I will add the new O_COLEMAK patch.

How does that sound?

**Comment by KlzXS** [comment]
@luukvbaal Oh, I thought you were invested in it since you recently updated it. My bad, I didn't look into the origin of that patch.

@jacmoe I think it can stay as it is for now. When you learn how to export a diff and make a patch that would satisfy an average Colemak user you can rename the old one as well.

**Comment by luukvbaal** [comment]
Yeah no need to rename until we have a new patch.

> I learn how to export a diff.

The patches use the `git diff` format. Run `git diff HEAD^ > colemak.diff` after committing your changes.

**Comment by jacmoe** [comment]
@luukvbaal Thanks! It's been over a decade since I last made a patch on the command-line.

@KlzXS Sounds great!
I will probably have to create two patches: one for colemak users who want to use the VIM keys, and one for colemak users who prefer to use NEIO. The Gitlab fork uses the latter. However, I get the feeling that the vast majority are VIM'ers.

`colemak` and `colemak-neio` ?
