### ISSUE TITLE
preview-tui: Directory preview is buggy

### ISSUE THREAD

**Issue by zzReno** [jarun/nnn#1594]
I don't change anything!
![image](https://user-images.githubusercontent.com/47785806/220348917-83f4f489-c153-4883-b795-a5e4785cdead.png)

**Comment by N-R-K** [comment]
Are you on latest `preview-tui` ?

There was some change to the `preview-tui` env handling recently.

**Comment by zzReno** [comment]
> 

Yes, I'm using `preview-tui`.
Where to see the change, bro?

**Comment by luukvbaal** [comment]
A [change](https://github.com/jarun/nnn/pull/1580) was made exactly to avoid this kind of issue🤦🏻
A `$NNN_PAGER` env variable was introduced instead of using the shell's `$PAGER`. The default value of `$NNN_PAGER` includes the `-R` flag so I'm not sure why it would not interpret the escape sequences unless you have `$NNN_PAGER` defined.

**Comment by zzReno** [comment]
> 
Thank you, bro.
I use [your new preview-tui file](https://raw.githubusercontent.com/luukvbaal/nnn/80c07741e565c79305d476dd3b7fb17b32ce7f32/plugins/preview-tui). It must be a problem of variable: `$NNN_PAGER`(new file) and `$PAGER`(old file)
Now, this problem is solved! Thank you!
