### ISSUE TITLE
Consider moving away from ncurses to vty

### ISSUE THREAD

**Issue by krishnakumarg1984** [jarun/nnn#160]
The `ncurses` dependency prevents native compilation on `windows`.  There is a cross-platform alternative [`vty`](https://github.com/jtdaugherty/vty) that could be potentially used as an `ncurses` substitute.  If this is the case, a native build for windows would be possible by using `mingw`

**Comment by jarun** [comment]
I cannot learn a new lazy functional programming language and re-implement a C program in it to satisfy your requirements.

Also, I must repeat myself (ref: https://github.com/jarun/nnn/issues/146#issuecomment-442216033), please raise new feature requests in the ToDo List thread instead of raising issues because it's not a defect if it's not even supported.

**Comment by jarun** [comment]
BTW, as you are interested in this, can you try and compile `nnn` with pdcurses? http://pdcurses.org

`vifm` does the same thing. I am adding a ToDo.

**Comment by sjmulder** [comment]
I can’t say for pdcurses but I recall nnn worked well with {Net,Free,Open}BSD curses.
