### ISSUE TITLE
"src/nnn.c:1341:2: warning: array subscript is above array bounds"

### ISSUE THREAD

**Issue by sjmulder** [jarun/nnn#165]
Just a heads up as I couldn't tell if the warning is valid on first glance. Building on NetBSD:

```
$ gmake clean; gmake
rm -f -f nnn nnn-2.1.tar.gz
cc  -O3 -Wall -Wextra -Wno-unused-parameter -D_NETBSD_SOURCE -D_XOPEN_SOURCE=500 -I/usr/pkg/include -I/usr/pkg/include/ncursesw   -o nnn src/nnn.c -L/usr/pkg/lib -lncursesw 
[...]
src/nnn.c: In function 'xreadline':
src/nnn.c:1408:2: warning: array subscript is above array bounds [-Warray-bounds]
  wcstombs(g_buf + ((NAME_MAX + 1) << 4), buf, NAME_MAX);
  ^
```

**Comment by rillig** [comment]
The warning is valid. `g_buf` has 5120 bytes, and `NAME_MAX` is defined to 511.

**Comment by jarun** [comment]
Please test with the patch and update if you still see any issues.

**Comment by jarun** [comment]
Awesome! Thanks for the follow up. We are good with Ubuntu and masOS as Travis confirms.

**Comment by rillig** [comment]
Even though it works for the current version of NetBSD, the fix is obviously cheating. The same problem would appear again if `NAME_MAX` would be increased to 2047 one day.

The code compiles even when the warnings are enabled, which makes it possible that this bug is hidden until it crashes the program.

To fix this properly, there should at least be a [static_assert](https://stackoverflow.com/questions/3385515/static-assert-in-c) to make sure the buffer can never be overflown.

**Comment by jarun** [comment]
@rillig please raise the PR.

**Comment by jarun** [comment]
I have now handled this with the explicit intention of choosing size of the buffer.
