### ISSUE TITLE
Strange behaviour when opening an empty file 

### ISSUE THREAD

**Issue by AvianY** [jarun/nnn#187]
I am using zsh in alacritty.
When I try to open a file (with enter key or "L"), that is empty, it seemingly doesn't do anything, but instead starts to behave strangely. 
I have to press each key twice to do something. And after I close nnn, a new "xterm" terminal opens up vim with that empty file I tried to open before, opened.

I apologise if this has been solved before, but I couldn't find anything like it

**Comment by jarun** [comment]
1. please try on master
2. try a different terminal emulator e.g. the default on your system

**Comment by jarun** [comment]
3. try an empty zsh configuration.

I have tested `nnn` latest master with zsh and alacritty and everything works as expected. This should be a local issue and I am not sure I can do much about it.

**Comment by AvianY** [comment]
I sort of figured out the problem... it's complicated.
If I open the empty file with xdg-open, it open up in the same terminal just as I want. If I open up with mimeopen, it will do the same thing that nnn does right now.

So I uninstalled mimeopen (the package name on manjaro is perl-file-mimeinfo) and now it doesn't open with mimeopen, but xdg-open instead.
*BUT* now xdg-open changed the  way it opens it. It opens it in a web browser.... what is going on?...

**Comment by jarun** [comment]
Probably you are seeing issue #181. `nnn` supports only `xdg-open`.

**Comment by AvianY** [comment]
I can open it with xdg-open and it works as it should. But when I try to open it inside *nnn*, it will open it in browser instead, *but* only after I close the terminal in which *nnn* is opened... any idea?

**Comment by AvianY** [comment]
yes, I am

**Comment by AvianY** [comment]
when I am in zsh, I get different behaviour with xdg-open, than when I am in bash. When I am in bash, I get the same behaviour as in `nnn`

**Comment by jarun** [comment]
if the empty file is `abc`, what is the o/p of `touch abc`?

**Comment by jarun** [comment]
sorry, `file abc`?

**Comment by jarun** [comment]
Also, in your file manager, if you right click and see the properties which is the opener?

**Comment by AvianY** [comment]
1. empty
2. Vim

**Comment by AvianY** [comment]
This is all so strange. `xdg-open` by default performs as it should. If I run `xdg-open` from another app, such as `lf` or `nnn`, it will open the file in a browser.

**Comment by jarun** [comment]
when you run xdg-open from a terminal, it can run vim because vim is a terminal utility.

when you invoke it from another utility, i believe xdg-open detects it's is not called from a tty and it opens in the next best suitable gui application.

Anyway, it's not an issue with nnn and you have the key `e` to edit the file in VISUAL/EDITOR.

**Comment by kajzersoze** [comment]
I just tried this and I can confirm that this is happening.
From other terminal I made a new file with `touch test.txt`
Then from `nnn` I tried to open that file and `nnn` went nuts, had to kill the process eventually.
Using nnn v2.2

**Comment by jarun** [comment]
To be more accurate for your cases, here: https://github.com/jarun/nnn/blob/master/src/nnn.c#L2764

`file` returns empty so the file cannot be opened in VISUAL/EDITOR. The next thing is xdg-open. Can you guys confirm if the opener is indeed `xdg-open` for you using DEBUG logs?

**Comment by jarun** [comment]
@AvianY when you explicitly call `xdg-open filename` which application does it open in - vim in the same terminal OR vim in a new window?

**Comment by AvianY** [comment]
It opens in the same terminal

**Comment by AvianY** [comment]
how do I use "DEBUG logs" ?

**Comment by kajzersoze** [comment]
Problem is somewhere inside `nnn` and it's `nnn` only.
1. `touch test.txt`, creates empty file.
2. `xdg-open test.txt` , file opens normally  with Vim, which is my default editor.

Now, I don't care much about this problem because I don't have empty files that I open with `nnn` , but had enough time to test this issue out of curiosity.
Basically I'm just confirming this issue and explained how I reproduced it.

If the file is not empty there's no problem.

**Comment by jarun** [comment]
@AvianY 

Compile `nnn` with `make debug` for the debug logs enabling. You can debug print the opener.

**Comment by jarun** [comment]
If I set the open with application to `vim`, and issue `xdg-open` file in terminal, I see:

```
$ xdg-open abc
Vim: Warning: Input is not from a terminal
~$ Vim: Error reading input, exiting...
[2;2RVim: Finished.
```

**Comment by jarun** [comment]
I think the problem is `xdg-open` is behaving differently in different OSes. To handle this case I have an easy solution:

If the file is a not a text file and the size is 0-bytes, open the, when Enter is pressed, show a message: `empty file - use open with or edit`.

**Comment by AvianY** [comment]
1. I compiled it, but I still don't understand how to debug anything... could you please write detailed steps or send a link
2. I have just noticed that when I open an empty file with xdg-open, it will open it in vim in read-only mode

**Comment by jarun** [comment]
> It opens in the same terminal

So you mean the cli vim, right? (note that `nnn` assumes xdg-open with open the file with a gui application)

What happens if you set the open with application to some GUI editor, e.g. mousepad/leafpad/gedit and then try to open an empty file with `nnn`?

**Comment by kajzersoze** [comment]
Hahah, ok I won't bother you anymore.
It's a little weird though, using terminal file browser which assumes you will open GUI utility instead of a terminal one.
Besides, you shouldn't care about file size, let OS handle that.
Letting this go, good luck.

**Comment by jarun** [comment]
> It's a little weird though, using terminal file browser which assumes you will open GUI utility instead of a terminal one

No it's intended. That's why `xdg-open` is used: https://www.freedesktop.org/wiki/Software/xdg-utils/

to integrate with the desktop environment from the terminal.

`nnn` has no way to know if the intended utility will be a terminal one or gui one. `nnn` _assumes_ it's a gui one because that's the goal of the project - to integrate the terminal with the DE.

I was thinking of handling the 0-byte file _specially_ so it doesn't lead to the weird scenario. But I can't reproduce it.

Now, if you set the file to be opened with a gui editor (other than vim), does it work as intended?

**Comment by kajzersoze** [comment]
I don't have a gui editor, otherwise I would try it.
Also, I'm not using DE but WM.

Weird that you can't reproduce it, it's really happening.
Not weird but I'm not sure why that is.

I'll try later to patch nnn and use mimeopen instead of xdg-open, to see will it change anything.

Again, I asked about 0byte file checking inside of nnn because I don't have a problem with xdg-open emptyfile, so I have to assume that there's a problem somewhere inside nnn.

Have to go now for few hours but I'll let you know whether mimeopen changed anything or not.

**Comment by jarun** [comment]
> so I have to assume that there's a problem somewhere inside nnn

please refer to the code.

**Comment by jarun** [comment]
![](https://i.imgur.com/sAoxNUt.jpg)

manjaro-xfce-18.0.2-stable-x86_64
live system, no modifications

I can see the "open with" application is "mousepad" from thunar and `nnn` opens the 0-byte file in mousepad.

`nnn` is for gui-integration. `xdg-utils` are also about desktop integration: https://www.freedesktop.org/wiki/Software/xdg-utils/

Please set your "open with" to a gui editor. Setting it to a CLI editor (like vim) would lead to unexpected behaviour as `nnn` assumes the default app is a GUI one and sets the exec() flags accordingly.

**Comment by jarun** [comment]
I have added a new config option to _guard_ this case for accidental keypress. Yes, it can be annoying.
