### ISSUE TITLE
Feedback for selection of files

### ISSUE THREAD

**Issue by pglira** [jarun/nnn#196]
I'm using nnn since I've seen it in the video of Luke Smith. Yes, and it's simply great. I'm impressed by its concept, the simplicity and the gain in productivity. However, there is just one small reason why I stopped using it. When selecting files/folders, there is no kind of feedback (e.g. another color, italic font, a simple dot, whatever). I simply don't want to check each time after selection the list with `y`.

**Comment by jarun** [comment]
`^Y` says `selection on` when you start and `selection off` when you press it again.

Visual selection feedback is not planned. We don't want to read the copy list and redraw the window each time a file is selected. Other than that computation, there are cases where a file is removed, the sort order is changed an so on...

I understand the current provision doesn't match your expectations. But this is the best we can do at the moment.

**Comment by jarun** [comment]
One more note on this - `nnn` supports selection across dirs. This was added based on user request. I can't have a _smart_ way to remember the files which were marked in another directory. The only way is to compare each entry against the entries in the selection list and add a visual indication. That's too much of additional processing.

**Comment by pglira** [comment]
Yes, I know, the possibility to select files among different folders is great. However, especially when moving or deleting files (more critical than just copying) I need to double-check each time the selection list. And also it feels a little bit strange to select something without getting the feedback that I'm used from any other file manager.

**Comment by jarun** [comment]
> I need to double-check each time the selection list

I select files using `nnn` daily (in fact it is the only file manager I use). And I seldom look at the selection list because:

- I already know which files I am going to cherry pick, the selection doesn't drive that
- there is a visual feedback, the selected file path flashes in the status bar

But I do understand the difference in personal use cases/preferences.

> feels a little bit strange to select something without getting the feedback that I'm used from any other file manager

The workflows in `nnn` are different from other file managers. I can't compromise the performance and go for full file name matches to deliver the workflows in other file managers. As I mentioned earlier, if I had an algorithm that meets both the ends, I would have added that already.

**Comment by jarun** [comment]
@pglira @kxzaon @breisa selected files are indicated by a `+` at the beginning now.

**Comment by pglira** [comment]
Thank you very much!
