### ISSUE TITLE
recent file manager comparisons

### ISSUE THREAD

**Issue by buffet** [jarun/nnn#211]
There are these shiny, new file managers...

Could you add comparisons to them in your Comparisons section?

**Comment by jarun** [comment]
Yes, there are some very recent file managers (so I have updated the question to make it generic). However, you may have noticed the comparison table has a list of some popular FMs which existed even before `nnn`. I don't have any plans to add new ones.

**Comment by jarun** [comment]
In fact, even from the earlier utilities, I have removed ncdu from the list last month as it's not a file manager. I am also planning to drop ranger because it's in an interpreted language and is no match for the performance you get in native (benchmarks - https://benchmarksgame-team.pages.debian.net/benchmarksgame/faster/python3-gcc.html). People who are on an i7 with SSD may want to ignore that but It becomes necessary when you run `du` on a nearly full 1TB disk or intend to get some speed on the Pi or the Termux environment in resource constrained Android devices. The other 2 would stay - they are both excellent file managers.

**Comment by jarun** [comment]
It's a good question. Keeping the issue open.

**Comment by jarun** [comment]
Closing as there's no response. Thanks for bringing it up anyway.

**Comment by buffet** [comment]
> Closing as there's no response. Thanks for bringing it up anyway.

Sorry, I thought you were just leaving a note to yourself.

If you would share the benchmarks, I could run them. I got cfiles, lf, filet, and of course nnn to compare, anything I'm missing you'd want me to benchmark as well?

**Comment by jarun** [comment]
No plans to add anything else as I mentioned. The ones mentioned are the ones which existed earlier. There can be newer FMs faster or slower than `nnn`, and if we continue to compare, the list would never end. As I explained - I set out to write `nnn` with a goal and that's met. That's reasonable enough for me.

**Comment by buffet** [comment]
Saying it's the `fastest and most lightweight` (probably) filemanager is a lie then though. I could state the same about literally everything.

It's just `fast and lightweight` then.

**Comment by jarun** [comment]
> is a lie then though

How come? You are not quoting the full sentence there.

It says _probably_ and is meant for the user who is trying out `nnn` - _you have ever tried_. That doesn't mean it IS the fastest file manager ever written or would be written.

**Comment by buffet** [comment]
Why the benchmarks if you don't really care about stating facts?

**Comment by jarun** [comment]
Because I tried those popular FMs before I set to write a file manager.

**Comment by buffet** [comment]
So it's the fastest and most lightweight file manager *you* (not the user) have ever tried, and that's only because you don't care about trying any alternatives since?

**Comment by jarun** [comment]
You do have a point there. The advantage of being the author is I can always make things work in `nnn` and so I don't really look out for a new solution.

I updated the documentation. Thanks for being patient with me.
