### ISSUE TITLE
Consider changing the way file openers are chosen

### ISSUE THREAD

**Issue by throwaway217** [jarun/nnn#24]
Currently the only way to set file openers is before compiling or diving into specific toolsets like xdg.
While easy and documented, once this gets into repositories of non-source based distributions people won't manually rebuild the package in order to change some settings.
What do you think of the way ranger handles file openers ?

**Comment by jarun** [comment]
True, you need to add the mime if you want it handled in nlay. We are open to adding new mimes. No issues there. You just need to wait for the next release. Please consider the fact that nnn is hardly a month old.

> What do you think of the way ranger handles file openers ?

Kindly share a little more detail on this.

**Comment by throwaway217** [comment]
>Kindly share a little more detail on this.
Sorry I was under the impression ranger was using a unique mechanism for this for whatever reason.It just uses it's own inhouse file opener with mimes.

https://github.com/ranger/ranger/blob/master/doc/rifle.pod
https://github.com/ranger/ranger/blob/ccbcfc60810cba1ef79677a714746d40b34e34e7/ranger/config/rifle.conf

**Comment by jarun** [comment]
rifle is simply another opener. However, I didn't want to design nlay that way. We can still use the desktop opener which should take care of stuff nnn can't handle.

> once this gets into repositories of non-source based distributions

I think those distributions should have a central way of handling mimes instead of users choosing one for each type. nnn fallback opener should be set to that. The stated goal of nnn is desktop integration and re-use as much stuff as possible.
