### ISSUE TITLE
Allow to directly open an archive

### ISSUE THREAD

**Issue by rgtk** [jarun/nnn#261]
It would be nice to directly open archives like such: `nnn archive.zip`. Right now, this command prints "Not a directory".

It would make it possible to use as archive browser and open it from xdg-compatible apps.

**Comment by jarun** [comment]
I'll check it out.

**Comment by jarun** [comment]
From which app is this use-case not working? I can open an archive path directly from opera with `nnn` set as the default file manager.

**Comment by rgtk** [comment]
It doesn't work from any app.

It's interesting it works for you, since even directly `$ nnn archive.zip` doesn't work as mentioned above.

Would you mind sharing .desktop file and `$ xdg-mime query default application/zip`?

I am at v2.4

**Comment by jarun** [comment]
> It doesn't work from any app.

I mentioned from Opera browser. I am on master. Please try that.

Directly opening an archive (or any other type of file) from the cmdline is not supported. That's why I wanted to understand the use-case. From which app are you trying to open a file?

**Comment by bruce-hill** [comment]
I believe what @rgtk is requesting is to have nnn support exploring the contents of a zip file as if it were a regular directory. Vim's netrw does this for example (`vim --cmd "set nocompatible" archive.zip`). This would be a nice feature to have, but it may add a lot of complexity, especially to support stuff like opening files inside a zip file (extract the file to a temporary location, open the temp file, then update the archive with the temp file?).

**Comment by jarun** [comment]
My understanding was we can invoke `xdg-open` internally to do this (in a one-shot mode) if the path is not a directory. That would handle any type of mime.

The command `xdg-open abc.zip` opens the zip file abc which is the intended behaviour.

Note that `nnn` uses atool to show the contents of an archive. We can also detect the file type as an archive and open it using atool. But as you said, that would unnecessarily increase the complexity. When we talk about `xdg-...` and opening from an app we are already in the realms of X11 and desktop integration would be my preferred choice.

I had something at https://github.com/jarun/nnn/commit/ea3dce326ee17db0be208b11a9877989dff1052d which I reverted due to a regression which would even try to open binary files and `nnn` would go in a loop. I will try to work it out.

**Comment by jarun** [comment]
Please test the patch and confirm.

**Comment by jarun** [comment]
Reverted. I still see an issue - when you press enter on a binary while browsing the cursor gets busy for a while.

**Comment by jarun** [comment]
Please test with latest master. This should work as expected now.

**Comment by rgtk** [comment]
Works sweetly. Thank you @jarun!

**Comment by jarun** [comment]
Thanks for confirming. Please award a star if you like the utility.
