### ISSUE TITLE
[Feature request] Changing file entry order

### ISSUE THREAD

**Issue by magpie514** [jarun/nnn#267]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Ubuntu Linux 19.04 amd64/Android 4.4.4
[x] Desktop Environment: KDE Plasma 5
[x] Terminal Emulator: Konsole
[x] Shell: Bash
[ ] Custom desktop opener (if applicable): N/A
[x] Issue exists on `nnn` master

nnn is pretty excellent at doing management tasks, I've been making a habit of using it to do basic quick file management and directory navigation in both my desktop and phone and I'm pretty happy about it so far.

But I have found a little inconvenience, not really a dealbreaker, but using long file display is a bit distracting to me, and I find short file display to be too barebones. I'd be pretty good if it could be customized or reversed so instead of:
` <date> <perms> <indicators> <file/dir name> `
if can start with the file name first like:
`<file/dir name> <indicators> <perms> <date>'`
which is a more familiar layout, personally speaking.

Of course while technically a small change it's just a "would be nice to have" thing, so I understand if you find it not worth the effort, feel free to close the issue if so.

**Comment by jarun** [comment]
The first 3 fields are fixed-length while the file name field varies. The combined length of all the fields is limited by the number of columns your terminal has. So even if we show the names int he first column, we will have to truncate it when it's too long.

It's a huge amount of work to stabilize. we don't have that bandwidth.

You have the following options:

- use a wider terminal
- use `nnn` in the light mode where you see only the filename

**Comment by luukvbaal** [comment]
For anyone still interested in this I'm currently maintaining a [fork](https://github.com/luukvbaal/nnn) that implements this.

**Comment by Kabouik** [comment]
Thanks for it by the way @luukvbaal. I'm not using it currently because I don't use icons in `nnn` so having details before filenames like in `ls -la` is not a particular inconvenience for me. Also I was not sure the fork would be easy to maintain given how actively `nnn` is being developed. But I do like that your fork gives flexibility regarding the order I starred it because I may well try it some day.

This was already discussed recently and it was decided that the compilation option for custom column orders is out of scope for upstream, so I'm not commenting that, but what about the better (in my opinion) right-alignment of file sizes? I don't remember if it was decided to keep this particular feature out.

**Comment by luukvbaal** [comment]
> Also I was not sure the fork would be easy to maintain given how actively nnn is being developed.

I got rid of the custom ordering and further simplified the patch since last we talked about it. It's only ~80 LOC now(net diff(https://github.com/luukvbaal/nnn/commit/2956c9fc274a437b047a4a3e6c9f37c0cd0811c0 is actually smaller than upstream) and can usually just `git rebase` without issues so I'll keep maintaining it since I really prefer the names to be first.

> but what about the better (in my opinion) right-alignment of file sizes?

I assume you're talking about keeping the `.0` to align the file sizes. In my opinion it makes it easier to see relative file sizes and its simple change in `coolsize()`:
```diff
+if (i > 0 && i < 6 && rem) {
-if (i > 0 && i < 6) {
```
See the size columns in 
![image](https://user-images.githubusercontent.com/31730729/117514635-9a14b100-af94-11eb-8d43-c1df5e224142.png)

Don't think anyone responded to it in the previous discussion so not sure what others think of it.

**Comment by Kabouik** [comment]
> I assume you're talking about keeping the `.0` to align the file sizes. In my opinion it makes it easier to see relative file sizes and its a simple change in `coolsize()`:

Absolutely, I am referring to that. I actually I did reply in the previous discussion (but I'm not neutral, I was also the one [requesting the feature](https://github.com/jarun/nnn/issues/881#issuecomment-808417452)).

Glad to see it's a simple change I could make locally too, but I'm not a great git expert and am already struggling with my couple stashed changes at every update. Would love to see that implemented upstream. The only downside I can see is it would slightly clutter the view when file sizes are all round, but (1) it's the `details` view which can be toggled off at any time, (2) it's unlikely that all file sizes have no decimal, and (3) file sizes are already right-aligned, which hints that it's already meant to allow easy comparison of numbers (but fails to do so due to this slight issue).

**Comment by luukvbaal** [comment]
> but I'm not a great git expert and am already struggling with my couple stashed changes at every update.

I suggest keeping your personal changes in a git branch. Then you can easily generate a diff with upstream (to apply with `patch`) with something like `git diff <upstream>/master <branch>`. 

This [PKGBUILD](https://gist.github.com/luukvbaal/3c04845e89bfccc40baf969a46e93ba0)(beware this uses my fork as a base, adapt for upstream) automates the process further using the github diff url. Using this PKGBUILD updating for me amounts to `makepkg -i` on Arch Linux. I'm sure the same patching method could be applied to other distro's build scripts, or even a distro-agnostic build script.

**Comment by jarun** [comment]
> but using long file display is a bit distracting to me, and I find short file display to be too barebones.

When you have a long filename, it's something you want to see (as much as possible). What if there are 5 files with the same long prefix and only the last character is a changing index. We cannot drop that functionality.

If you prefer, feel free to use @luukvbaal's patch.

**Comment by luukvbaal** [comment]
@jarun if you hadn't noticed this is a really old issue, I just posted here for anyone who might come across it if they're interested in this feature.

> When you have a long filename, it's something you want to see (as much as possible). What if there are 5 files with the same long prefix and only the last character is a changing index. We cannot drop that functionality.

That functionality is not present on upstream though is it? The name is cut off at the end, same as on upstream. If anything my patch can show more of the file names in such a case due to optimizing the size column width to the longest entry instead of a fixed width.

**Comment by jarun** [comment]
> If anything my patch can show more

I think it will be the same if we fill to the last entry with the same columns in detail mode. However, now I remember we had the issue of dancing columns vs. the columns too far away.

**Comment by luukvbaal** [comment]
My representation shows more of the name in case the largest size entry is smaller than the fixed width of the size column.

Yeah if you consider the "dancing" an issue that can't be avoided unfortunately when optimizing for screen estate. It only happens when holding down <kbd>J/K</kbd> in a large directory however and my eyes are focused on the name(which is static) when scrolling so I don't see it as an issue.
