### ISSUE TITLE
Batch rename doesn't work on MacOS

### ISSUE THREAD

**Issue by relapi** [jarun/nnn#307]
Batch rename on MacOS doesn't work, I think due to xargs not having the `-d` option (used here): https://github.com/jarun/nnn/blob/master/src/nnn.c#L1174

Similar issue here: https://github.com/jarun/nnn/issues/143

**Comment by jarun** [comment]
Kindly submit a patch.

**Comment by jarun** [comment]
Please confirm the patch works.

**Comment by relapi** [comment]
That fixed it :) thanks so much ❤️ ❤️!

**Comment by jarun** [comment]
:+1:

**Comment by jarun** [comment]
Oops, my fix was completely wrong!

@0xACE can you please take a look what needs to be done here?

**Comment by jarun** [comment]
Sorry, I was requesting @ath3 to take a look.

**Comment by 0xACE** [comment]
I haven't been home in a while and kinda only have access from a android phone. Another concern I want to bring up is, are you 100% sure that file names are correctly "quoted" when you pass them to programs?

Because I recall at multiple times where files containing `spaces` or `'` or other wierd characters are opened incorrectly. I haven't researched it enough to tell what's going on, but commonly I don't trust xargs that much and tend to use it like so:

    ncp | xargs -d'\n' -I% myprogram "%"

to ensure that the file gets enclosed in quotes... Again I haven't researched or tested it enough to actually know how xargs handles the quotes, but I figured it would be  nice to bring it up to your attention so that maybe someone else could comment on correct usage of `xargs` and weird file names that can appear in the wild...

**Comment by jarun** [comment]
Your analysis is correct. The problem right now is macOS xargs doesn't have the `-d` option. I think we'll have to wait for @ath3 here.

**Comment by jarun** [comment]
@relapi For the time being you do have the option to install xargs from findutils on macOS (probably via Homebrew).

**Comment by jarun** [comment]
@relapi the issue should be fixed now. Please test and confirm.

Make sure you test with filenames having spaces, single/double quotes etc. in them,

**Comment by relapi** [comment]
@jarun That build seems to work (for files and directories), but throws an error on directories (even when hitting r but then not modifying anything)

```
mv: rename abc to abc/abc: Invalid argument
mv: rename def ghi to def ghi/def ghi: Invalid argument
```

given the following directory structure:

```
├── abc
│   ├── def.txt
│   └── hij lmno.txt
├── def ghi
│   ├── def.txt
│   └── hij.txt
├── test 'copy' 2 "copy".txt
├── test 'copy' 2.txt
├── test copy.txt
└── test this.txt
```

Regarding using xargs from findutils, I think going that route would be fine however that solution currently breaks all the commands in here https://github.com/jarun/nnn/issues/143 (with the current homebrew build)

**Comment by jarun** [comment]
I see. Then xargs from findutils is not the correct way to handle this.

I will check the issue.

**Comment by jarun** [comment]
Try now. I think the problem was the output was spewing.

**Comment by relapi** [comment]
@jarun 👍 Change looks good. Thanks for your work on this!

**Comment by jarun** [comment]
No problem! If possible, please consider donating a little to the project if you think it's worth.
