### ISSUE TITLE
Homebrew formula broken for --HEAD install

### ISSUE THREAD

**Issue by relapi** [jarun/nnn#308]
`brew install nnn --HEAD` results in the following error: `Errno::ENOENT: No such file or directory - scripts/auto-completion/bash/nnn-completion.bash`

I assume it's because the scripts were moved to `misc` here: https://github.com/jarun/nnn/commit/794a0e27091b63f997fc829d0288cde5a4a2edbd

**Comment by 0xACE** [comment]
Yes it seems like you found the correct commit that caused this incompatibility.

I'm not familiar with `brew` yet but I'm guessing your attention should be directed towards:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/nnn.rb#L20-L22

and have the `recipe` target `misc/...` rather than `scripts/...`

You could run this if you have `curl` and `sed` on your machine:

`curl https://github.com/Homebrew/homebrew-core/raw/master/Formula/nnn.rb | sed -e 's/scripts/misc/' > nnn_updated.rb`

I would send a pull request but their recipe is for v2.5 which is not affected by this change.

**Comment by jarun** [comment]
> I'm not familiar with brew yet but I'm guessing your attention should be directed towards

That's correct. We'' have to update the formula on next release.

**Comment by jarun** [comment]
I'll keep this open till next release.

**Comment by jarun** [comment]
Fixed at https://github.com/Homebrew/homebrew-core/pull/42831.
