### ISSUE TITLE
Change archive path(s)?

### ISSUE THREAD

**Issue by serussell** [jarun/nnn#311]
Creating an archive of files deep in a subdirectory, `nnn` roots the files at the home directory; this creates an archive with a deep tree structure.  Is there a way to change where the archive is rooted, say, in the current directory?  Or relative to the where the archive is being created? One of the two following behaviors would be less surprising, to myself, at least:

1) If the archive is being created in the same directory as the files being added, the archive would contain only the files, with no directory structure.

2) Better would be a path relative to where the archive is being created; this would be a super-set of the first case.  E.g., in directory `A`, tag files `a` and `b`.  CD to `..` and create an archive (`f`).  The zip would then contain entries `A/a` and `A/b`.  Without the CD (creating the archive in `A`), the archive would contain `a` and `b` with no paths.

What is surprising -- and I'm struggling to see the value -- is the current behavior, where the archive contains entries with full paths from ${HOME}.

**Comment by jarun** [comment]
This happens when you _select_ some files and archive those, not when you archive the current entry. `nnn` supports selection across directories. While this may look surprising there are 2 good reasons this is done:

- the paths to the directories are preserved when multiple files are selected from multiple paths. This makes it simpler for the user to identify which file came from where on extraction.
- If there are 2 files with the same name from 2 directories there wouldn't be any conflict

So when you pick a file from a deeply located path you get it extracted with a deeply rooted path. `nnn` doesn't add the deeply rooted-ness to the file.

Now that you know this, you can try the following:

- move the folder with the deeply rooted path to a different location and archive it
- select the files you need to a different location and archive them

One can argue why `nnn` doesn't do the conflict resolution to check if file names are same. But that wouldn't help with preserving the directory paths and doing that resolution for 10K files selcted together would be quite intensive.

**Comment by 0xACE** [comment]
Hey I've been away but I should mention:

The feature you are requesting has actually been implemented and I'm using it locally. It works by stripping the selected files `fullpath` with `CWD` basically... I don't know what consequences this can have but it fits my use case better... For example what happens when `CWD` doesn't match some of the selected files? In my patch it simply doesn't strip the parent folders that don't match the exact path, so it could have problems with symbolic links...

I only ever copy a full path to a file if it's meant for a full archive/storage/backup sort of situation. For a regular `.zip` i just select some files and mail them to friends... I don't expect them to get `/home/ace/my/private/folder/structure/THE_INTENDED_FILE.JPG`, I want them to just get a archive with `THE_INTENDED_FILE.JPG`

(Sry if this msg doesn't make sense I'm in a hurry)

**Comment by jarun** [comment]
@0xACE can you please share your patch as well? Someone looking for this may get an idea from it.

**Comment by serussell** [comment]
@jarun What you describe would make sense, except:

* The tagged files were all in the same directory, and 
* The archive being created was in the same directory

The archive created had full paths, despite there being only a single path among all files selected, and (therefore) no possibility of duplicate file names.

E.g., to recreate:

1. `nnn` and navigate down into some sub-directory
2. Toggle selection
3. Choose two files from the current directory
4. Toggle selection
5. Archive

I think what you're suggesting is that `nnn` only performs a very basic, simple check: if there are more than one file in the selection, then it appends the full paths.  I guess I'd expect some simple logic like [this](https://play.golang.org/p/YV4K8gWUeY2).

**Comment by 0xACE** [comment]
I should mention that #313 is very naive to solving this issue. For example if you select files outside of the `CWD` they will be using the `fullpath` rather than relative to `CWD`. But it makes my life easier, so I keep it locally at least.

Since `nnn` is written in `C` I chose this simple method over than over complicating it. Yes the original plan was to use fully relative paths but atm I would put higher priority on other tasks.

**Comment by jarun** [comment]
@0xACE 

> very naive to solving this issue

I think this is the only way to do it other than having to take really roundabout routes. In the PR, can you make the similar change for macOS as well?

Of course, the string manipulation would take its time on low-power handhelds, really long paths and 10K files.

I have conflicts regarding accepting this mainline. Preserving full paths is totally correct if you consider the fact that selection is a central idea in `nnn` and it supports selection from anywhere, not just the current directory. And frankly speaking, it doesn't look like inconvenient at all to me because of the correctness of the paths. If I archive some system files and send it to someone else to use in his system, the recipient knows exactly where the files belong to. You don't need to tell him to go to a certain directory and extract the files.

Regarding user convenience: if you have selected files from the same location, after extracting the archive:

you can pin a directory, easily navigate into the archive structure with `nnn`, reach your files, press `Y` to select all, jump back to the pin and move the selection to it. I am not sure if it's really that tedious.

Probably I would accept this change if we have 10 users asking for it. Does that make sense?

**Comment by serussell** [comment]
> Since nnn is written in C 

Doh!  Yeah, sorry, my example was in the wrong language; it does get more hairy in C without the convenience functions or pulling in libraries.

@0xACE's #313 does solve my original request, though, and since (IME) it solves the common case, I think it's great.

**Comment by 0xACE** [comment]
> I have conflicts regarding accepting this mainline. Preserving full paths is totally correct if you consider the fact that selection is a central idea in `nnn` and it supports selection from anywhere, not just the current directory.

Perhaps I haven't mastered `nnn` yet. But I still can't tangle my mind around how to use "multiple instances" of `nnn`. If you have 2 instances, both which has made their own selections. How do you access the selection made by the other instance? Do you clear both with `KK` first?

Yes making selections over various directories is cool. But I haven't used it as of today. This may be because during my entire life of using other file managers: they never offered this feature, so I haven't gotten used to the fact that it's a possible operation.

>And frankly speaking, it doesn't look like inconvenient at all to me because of the correctness of the paths. If I archive some system files and send it to someone else to use in his system, the recipient knows exactly where the files belong to. You don't need to tell him to go to a certain directory and extract the files.

Maybe we are targeting different use cases. Maybe your approach fits a "administrators" perspective. But it hardly translates for a regular "end user".

The use case you present has only ever been done in my life when I have been dealing with full archives or backups for files in `/etc` and what not. So that when I recover those backups: they will end up in the right place automatically.

As a every day, common user, I want to `zip` my files and send them to friends or colleagues. I can assure you that my friends and colleagues don't want to receive `zip` files which has a folder structure like so: `/home/ace/pictures/2019/july-europe-with-friends`.
I would just send them the `zip` with `europe-with-friends/` or a `bare` `zip` with with just the `jpeg`s and let them choose to extract as `sub-dir` or `bare`.

Imagine unpacking that archive on windows, you would end up going deep into a tree structure just to reach the intended file.

I would argue that the common practice for users is this experience:
![rightclick](https://user-images.githubusercontent.com/1482942/62418242-26c66880-b665-11e9-8deb-a58bd66af2b3.png)

This lets you quickly select the files you want to `zip` and send them to a new destination/person. And receiver can quickly `unzip` it into a `sub-directory` or `bare`.

As you may have witnessed from "casual users": people commonly `unzip` onto their desktop and use the file immediately from there.

> Regarding user convenience: if you have selected files from the same location, after extracting the archive:
> 
> you can pin a directory, easily navigate into the archive structure with `nnn`, reach your files, press `Y` to select all, jump back to the pin and move the selection to it. I am not sure if it's really that tedious.

That's a cool trick. But I would argue that it's too much to ask for an end user.
 
> Probably I would accept this change if we have 10 users asking for it. Does that make sense?

To me it is not the end of the world if it doesn't get adopted upstream. As I have made peace with your decision. But I would say from a average user perspective: the relative path makes more sense.

_(Fun fact: the picture was attached with the new drag-and-drop support. From CLI to the web)_

**Comment by jarun** [comment]
> If you have 2 instances, both which has made their own selections.

The process-local selection gets the priority. If it's empty (use `^Y^Y` to empty selection) you can access the selection in the other one.

Also, note that we use a single `.selection` file. So the file has the contents from the last process that made a selection.

> Maybe we are targeting different use cases.
> That's a cool trick. But I would argue that it's too much to ask for an end user.

Possible. But I think I would like users to get used to something new. It's not complex, maybe it needs a few steps extra. But, if you want to implement this correctly indeed, there's only one way:

- initiate the archiving process and then do the selection with only file names (the framework exists but you need a new archive_selection file)
- limit it within the directory (if user moves, exit the archive workflow)
- call the current API to archive

That isn't very easy to achieve. You have to invoke selection workflow within archiving.

Otherwise, please check if there is any generic CLI archiver which supports stripping the path completely. If there isn't try submitting a patch to bsdtar/atool to do it.

> the picture was attached with the new drag-and-drop support

Cool! Please add the wiki entry. I never use the GUI file manager nowadays but I can see how it's useful for end users.

**Comment by 0xACE** [comment]
> > If you have 2 instances, both which has made their own selections.
> 
> The process-local selection gets the priority. If it's empty (use `^Y^Y` to empty selection) you can access the selection in the other one.
> 
> Also, note that we use a single `.selection` file. So the file has the contents from the last process that made a selection.

Okay, then it works sort of like I expected. Though doesn't `^Y^Y` clear `.selection` ?

The problem with the drag and drop scripts I will upload is:

I sort of miss the functionality to `use .selection` instead of the one `nnn` is holding, and `^Y^Y` will clear `.selection`... The current method requires the user to clear the `selection` with `^Y^Y` **BEFORE** they run the drag and drop script...

> > Maybe we are targeting different use cases.
> > That's a cool trick. But I would argue that it's too much to ask for an end user.
> 
> Possible. But I think I would like users to get used to something new. It's not complex, maybe it needs a few steps extra. But, if you want to implement this correctly indeed, there's only one way:
> 
>     * initiate the archiving process and then do the selection with only file names (the framework exists but you need a new archive_selection file)
> 
>     * limit it within the directory (if user moves, exit the archive workflow)
> 
>     * call the current API to archive
> 
> 
> That isn't very easy to achieve. You have to invoke selection workflow within archiving.
> 
> Otherwise, please check if there is any generic CLI archiver which supports stripping the path completely. If there isn't try submitting a patch to bsdtar/atool to do it.

Yeah that's a bit over the top... To my it's simply about archive my selection from "where I'm standing". But in the end I will maintain my personal branch of this function, so no hard feelings from me :)

> > the picture was attached with the new drag-and-drop support
> 
> Cool! Please add the wiki entry. I never use the GUI file manager nowadays but I can see how it's useful for end users.

Yeah I have to clean up the clutter. I don't feel safe in shell scripting, I feel like I'm quoting everything, but I guess that's a good thing...

**Comment by jarun** [comment]
> Though doesn't ^Y^Y clear .selection ?

 No.

> The current method requires the user to clear the selection with ^Y^Y BEFORE they run the drag and drop script...

Let the script clear it (if possible). If you do, please document the procedure.

**Comment by serussell** [comment]
@jarun, despite my code being in the wrong language, I'm curious about what is "incorrect" about the approach. Given that all paths in `.selection` are rooted at the same place, what is the problem with stripping directories from the root of the tree until the tree branches?  Is it technical, or do you think that it's confusing or wrong behavior?

I'd be surprised if a significant percent of uses of `zip` or `tar`, across all uses in the world, were rooted in `/`.

**Comment by jarun** [comment]
@serussell please raise the PR.
