### ISSUE TITLE
Don't use $XDG_CONFIG_HOME for runtime data

### ISSUE THREAD

**Issue by lahwaacz** [jarun/nnn#339]
The `$XDG_CONFIG_HOME` path should be used only for config files. But since nnn does not have a config file, `$XDG_CONFIG_HOME/nnn/` is being abused:

- I suggest to move runtime files like `.selection` and `.lastd` to `$XDG_RUNTIME_DIR` which complies to the standard (and it is usually located on tmpfs).
- I'll excuse `plugins/` although they are not configuration either, but there is no better default location. But nnn should not default to creating an empty directory if it does not exist.

**Comment by jarun** [comment]
Made the headline read a little less like it's the end of the world. We'll consider this.

**Comment by jarun** [comment]
From the `XDG` docs:

```
$XDG_RUNTIME_DIR defines the base directory relative to which user-specific non-essential runtime files and other file objects (such as sockets, named pipes, ...) should be stored.
```

- Neither the `.selection` and nor the `.lastd` files are _non-essential_. Many of the vital functionalities of `nnn` work using the `.selection` file. Plugins use it all the time. The `.lastd` file is accessed even after `nnn` quits.
- The `$XDG_RUNTIME_DIR` is not a constant one and I don't want users to keep changing their scripts from system to system.
- I don't intend to maintain unnecessary code paths when it's not required.

**Comment by lahwaacz** [comment]
- As far as I can tell, `.selection` and `.lastd` can be considered non-essential, because if they were suddenly deleted, nnn would not crash but some functionality would break. This (or worse) can be said for virtually any program storing any files (like sockets or named pipes which are used as examples in XDG) in `$XDG_RUNTIME_DIR`. Even non-essential files are needed for something, otherwise they would not exist at all. Also note that the purpose as nnn's `.selection` and `.lastd` files is the same as that of sockets or named pipes - communication with other programs (or plugins). As for `.lastd` being accessed after nnn quits - if you are really concerned with this, I don't understand why the _config_ directory seems more suitable to you.
- Users should use the `$XDG_RUNTIME_DIR` _variable_ and not its _value_ in their scripts.

On the other hand, from the XDG specification:

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored.

Neither `.selection` and nor the `.lastd` files are _configuration files_, so the bug still stands. If you insist that `.selection` and `.lastd` are non-essential and want to use persistent location, use `$XDG_DATA_HOME` instead.

Please consider this again.

**Comment by jarun** [comment]
> Users should use the $XDG_RUNTIME_DIR variable and not its value in their scripts.

Each and every path in XDG has this catch - _If $XDG_XXX_DIR is not set_... And that's what makes it so goddamn hard to keep supporting this horseshit. It's not a spec, it's just a guideline that's lenient enough to say it's OK if you don't follow me. So eventually devs have to keep supporting multiple paths (which translates to redundant code in their lingo).

It's a wrapper over the standard Unix locations. For example, there was never any issue with the default `~/.config` to begin with, symbolic links worked all the time. This is the problem with open source, people keep wasting their time and the time of others in discussing shit stuff and getting concerned over trivia as if that's the most important aspect of the actual product. If you are unable to use `nnn` because it stores 2 important files in a dir that belongs to itself, please feel free to fork and have your own project. I am not going to waste my free time discussing and considering this when no one ever felt like popping in and contributing a line of code in this area while it was being developed in the past 2.5 years.

**Comment by jarun** [comment]
Note: I have marked the thread as off-topic because of my own arguments here. I admit I am tired of having to address concerns without material contributions in areas which are not closely coupled with the main program and could be contributed to easily. It's been many years I'm doing this and at this point in life if I can spend 5 extra minutes with my son with a peaceful mind or enjoy a cup of coffee with my wife this beautiful morning without having to have these things poking in my brain I prefer that a thousand times.
