### ISSUE TITLE
What is the leader key on Linux, and how can I change it?

### ISSUE THREAD

**Issue by mrbig033** [jarun/nnn#342]
Title.

**Comment by jarun** [comment]
There are two leader keys (on any OS): <kbd>,</kbd> and <kbd>^/</kbd>.

You can look them (and all other shortcuts) up in `nnn` by pressing <kbd>?</kbd>.

To change a keybind you'll have to compile `nnn` (not that difficult because of minimal deps). However, I think if you press <kbd>?</kbd> you'll realize why the keybinds are not readily modifiable.

There was a time they were modifiable and we were spending more time on resolving custom keybind conflict issues than on actual development.

**Comment by mrbig033** [comment]
> There are two leader keys (irrespective of OS): , and ^/.
> 
> You can look them (and all other shortcuts) up in `nnn` by pressing ?.
> 
> It documented as well: https://github.com/jarun/nnn#keyboard-and-mouse
> 
> To change a keybind you'll have to compile `nnn` (not that difficult because of minimal deps). However, I think if you press ? you'll realize why the keybinds are not readily modifiable.
> 
> There was a time they were modifiable and we were spending more time on resolving custom keybind conflict issues than on actual development.

May I suggest you change "lead key" to "leader key", in order for a regular search to find this information?

**Comment by mrbig033** [comment]
> To change a keybind you'll have to compile `nnn` (not that difficult because of minimal deps).

I'm wasn't REALLY interested in changing this keybinding, but it seemed like a question that would lead me to how the leader key works on `nnn`. Thanks.

**Comment by jarun** [comment]
> May I suggest you change "lead key" to "leader key", in order for a regular search to find this information?

It's mentioned as `Leader` in the docs: https://github.com/jarun/nnn#leader-key

It's mentioned as lead in help as I wanted to save a few bytes and keep the help a little concise.

**Comment by mrbig033** [comment]
> > May I suggest you change "lead key" to "leader key", in order for a regular search to find this information?
> 
> It's mentioned as `Leader` in the docs: https://github.com/jarun/nnn#leader-key
> 
> It's mentioned as lead in help as I wanted to save a few bytes and keep the help a little concise.

I understand, but in the Keyboard and mouse section, it is referred as `lead` instead. This screwed-up my `Ctrl+f`m and made me create this silly issue.

**Comment by 0xACE** [comment]
> it is called `lead key` instead. This screwed-up my `Ctrl+f` and made me create this silly issue. `leader vs lead key`. It's just a small inconsistency, I see no reason not to correct it.

If you hit `?` in `nnn` you will see that the `help` list is very, *very* constricted. Therefor liberties has been taken to fit the help screen message within the assumed width of the terminal.

As you can see in

https://github.com/jarun/nnn/blob/master/src/nnn.c#L2818

The `show_help()` function is stupid simple, as to adhere to the project philosophy goals.

There are reasons for it being concise.

**Comment by mrbig033** [comment]
I just think it's inconsistent, that is all. If there's a case to be concise, then change the README to make  `leader` read `lead key` in all cases. You can always make a note that this is what some people usually call `Leader`. Problem solved.

**Comment by jarun** [comment]
@mrbig033 I think that's a very reasonable suggestion. I am going to update the README accordingly.

**Comment by mrbig033** [comment]
Thank you!

**Comment by ohcibi** [comment]
When I press `?` there is no mention of a "Lead" key but only a "bookmark key" (which I figure is the one since it is mapped to `^/`).

* The link to the readme above does not work anymore. The term "lead" does not exist in the current readme
* The only place in `man nnn` where a "Lead key" is mentioned, is the section for bookmarks. But it only tells to use the key but not which it is

This commit: https://github.com/jarun/nnn/commit/09083f3ed6749567c4e315a68f071811ee776f80 removes the section in question from the README without any reasoning. @jarun was the removal accidentally or intentional?

**Comment by jarun** [comment]
Lead key is gone in v2.9.  There's bookmark key and plugin key. I'll update the docs.
