### ISSUE TITLE
I cant make install

### ISSUE THREAD

**Issue by amoksito** [jarun/nnn#4]
I am having this error in Arch .. 

In the GNU C Library, "major" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "major", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "major", you should undefine it after including <sys/types.h>.

**Comment by jarun** [comment]
Do we have it in OS X as well?

**Comment by jarun** [comment]
This change fails on OS X: https://travis-ci.org/jarun/nnn/jobs/220695694

**Comment by jarun** [comment]
@shaggytwodope @zmwangx is there a way to setup an Arch Linux based build environment on Travis?

Also, <sys/sysmacros.h> is not available on OS X. Is there any generic way to fix this other than `#ifndef __APPLE__`?

**Comment by shaggytwodope** [comment]
@jarun I saw this a while back https://github.com/mikkeloscar/arch-travis but I have not had time to test in any way. But it may be the easiest method.
I'm not sure any other way to address this short of using `#ifndef` myself.

**Comment by jarun** [comment]
What happens if you do not include any of types.h or sysmacros.h explicitly on Arch? It works on Ubuntu. And [this](https://books.google.co.in/books?id=kCTMFpEcIOwC&pg=PA138&lpg=PA138&dq=sysmacros.h+missing+os+x&source=bl&ots=zvMwZN_zrB&sig=XbxTmdCe6nc4chBynRNZCz0TNyo&hl=en&sa=X&ved=0ahUKEwis-7fV5prTAhUcSo8KHYmbCNoQ6AEIMjAE#v=onepage&q=sysmacros.h%20missing%20os%20x&f=false) also says it may work.

**Comment by zmwangx** [comment]
> is there a way to setup an Arch Linux based build environment on Travis?

Probably not Travis, but it's very easy to set up a Arch VM. I recommend using the base box https://github.com/terrywang/vagrantboxes/blob/master/archlinux-x86_64.md with Vagrant which is how I get Arch.

What you really need here, though, is an up-to-date glibc.

>  Is there any generic way to fix this other than #ifndef __APPLE__?

Autoconf, `AC_HEADER_MAJOR`.

I don't think `__APPLE__` is appropriate here, it's clearly a BSD vs (very recent) GNU problem. And you can solve it by removing the `-Werror` flag, since it's just a deprecation warning.

> What happens if you do not include any of types.h or sysmacros.h 

That doesn't work on macOS. And other BSD variants, I would imagine.

**Comment by jarun** [comment]
I've started a build without `-Werror`. I also want to avoid conditional compilation as long as it's unavoidable. In the worst case, two new macros (based on latest GNU source) would suffice.
