### ISSUE TITLE
cd on quit not working

### ISSUE THREAD

**Issue by breuerfelix** [jarun/nnn#439]
first of all, thanks for this tool ! as a vim user i really appreciate the usage :)

i installed nnn via apt on ubuntu 18. i got nnn version 2.6.

i also got zsh as my shell, so i just created a script called `nnn.sh` and sourced it in my .zshrc.  
the content is from [this file](https://github.com/jarun/nnn/blob/master/misc/quitcd/quitcd.zsh)

i already echoed after the nnn "@" command and this worked. then i echod the path of NNN_TMPFILE which is also correct. the folder also exists. there is a plugins folder in this folder.

the problem: nnn is not writing anything to this file (it never even creates the file)

i quit nnn with q and with Q, both didnt work.

it does work when i press ^G ... is there any way i can make it work with a normal q or Q quit ?

for example q does just quit and Q does quit with changing the dir or vise versa (vise versa would be even better)

i also tried adding the source directly into the .zshrc file and not sourcing it from a .sh file... doesnt change the behaviour :)

cheers,

felix

**Comment by maximbaz** [comment]
The issue comes from the fact that you use `quitcd.zsh` from master branch, but your `nnn` is of an old version, so they are not compatible.

I would really recommend you to install the latest `2.9` release, there have been sooo many improvements done, you would love it 😉 

Debian packages are available as part of the Github release, just download them and install via `apt install ./nnn_2.9-1_ubuntu18.04.amd64.deb`

**Comment by breuerfelix** [comment]
since i didnt use nnn for that long, i am not able to tell the difference but i always like to be on the cutting edge :D

it works ! somehow i was not able to install it from the .deb file from the releases, even though i took the correct one for ubuntu 18.04 but i installed it from source which worked like a charm :)

thanks for this awesome quick help !
