### ISSUE TITLE
Feature request: Sort toggles on filtered results only

### ISSUE THREAD

**Issue by amanjitsk** [jarun/nnn#498]
Thanks for the amazing project. I encountered a use case for use sort toggles on filtered results only, but AFAIK nnn does not yet do this. So for example, if I cd into a directory with a huge number of files, and filter results, I would like to able to do a du toggle (or others) on just the filtered results. Right now it scans over the entire directory, which can take very long depending on the directory. It would nice if the sort toggles only operate on the filtered results.

Thanks,
Amanjit

**Comment by jarun** [comment]
This was working on master and broke due to commit 2d952795a848a8430e5ffcc5613fcedcd0d860b3.

You can use sort toggles on filtered results _on master_ for orders except du and au.

With du and au it's not possible as we need to rescan the directory for per-dir du, calculate total du etc. We also use the same field for size/du for dirs.

**Comment by jarun** [comment]
du and au should also work fine now. Please confirm.

**Comment by amanjitsk** [comment]
Sorry still doesn't work. I compiled from master right now

**Comment by jarun** [comment]
Steps please?

**Comment by jarun** [comment]
> Right now it scans over the entire directory

This still applies as du/au has to calculate the current directory usage. But the filter should remain intact.

**Comment by amanjitsk** [comment]
oh nvmd then it works I guess. I thought you meant du/au also works on the filters now. Thanks!
