### ISSUE TITLE
Add option to set archivemount path

### ISSUE THREAD

**Issue by f3l-x** [jarun/nnn#562]
Is it possible to add a new NNN_ variable for the path, where archivemount mounts the archives?
At the moment this is the nnn-config path. But sometimes i missed the unmount thing and the archives are still hanging around there....
My preferred way would be to mount the archives to an tmpfs mount, as mounting is my preferred action for just looking into archives, too.
With a NNN_ARCHIVEMOUNTPATH variable, this could be easily done.
Thank you very much!

**Comment by jarun** [comment]
- Note that we also take you inside the dir after we mount. Probably you can develop a habit to move up and press `u` on the dir once you are done checking the contents.
- If we do this for archives, we may have to do this for remotes as well, increasing the complexity.
- Currently for `unmount` on hover we also check if we are in the config dir or not. This restriction helps. if we are outside cfg dir we prompt. If we support mounting anywhere, this would also break.
- I think there is a a good reason the OS by default provides a default mountpoint like `/mnt` or `/media` for auto-mounts. Your case would apply here as well.

I would suggest 2 options:
- Something I do - have a bookmark to the cfg dir so it's easy to jump there and unmount in case you have left the config dir.
- Have a custom plugin to mount archives in `/tmp`.

I would like to avoid this significant a change because of personal habits. And there are simple workarounds.
