### ISSUE TITLE
Feature Request: Create a named session on startup

### ISSUE THREAD

**Issue by basbebe** [jarun/nnn#618]
I would love to have the possibility to open nnn with a named session.
As far as I understand it, Sessions can only be created from within nnn.
I like the idea of being able to open nnn with a specific session also from a script.

So for example `-N` creates a named session if a name is given.

**Comment by jarun** [comment]
> So for example -N creates a named session if a name is given.

Generating a _session file_ is not creating a session. When do you save the session? Why not use `-S`? I do not want to complicate sessions with tons of program options which everyone needs help with.

And it's a one time operation. Even if you want to save on quit if the session name you provided does not exist, you'll have to run `nnn` manually and press `q`.

**Comment by jarun** [comment]
More notes:

Even if I we want to save it on quit, what if user actually creates it in between? Do we first check if it exists? If we do save only when it does not exist, what if the user actually created one and then planned to remove it? The automagic thing fails on the face.

Also, what if an user inadvertently provides a wrong session name that doesn't exist. Would he want it to be created?

I could extend -S to support explicit session name but I don't want to extend it as a general option. I can understand `@` is dynamic, but in general a saved session means a well-defined and pre-defined starting point, say my project dir. I do not want to change that when I quit in some other directory at some point. While continuous sessions is great, I have noticed that even with `@` sometimes I end up starting in bizarre directories because the last time I quit there or I changed the sort order. It comes with an element of surprise. I am using it for a month now and I still experience that for time to time. So extending it to all sessions may do more harm than good to the user experience.

**Comment by basbebe** [comment]
The use case is like described in https://github.com/jarun/nnn/issues/619#issuecomment-636492192  
I just like the idea of creating a project (named after the foilder or a git project) and tie a nnn session to it. So that if I leave nnn for some reason I can come back to my project's nnn session.

That way I wouldn't have to remember to save a session.

I don't know if this makes sense.

**Comment by jarun** [comment]
> I don't know if this makes sense.

It does. However, as it's just a matter of a one-time setup and you _have_ to go manual when you want more than a single active context to be saved in the session, I would would leave it at manual handling.

**Comment by basbebe** [comment]
Could a session file easily be created by a script?

**Comment by jarun** [comment]
No. You have to create it as a _one time activity_. You have to open `nnn` and save with the preferred session name.
