### ISSUE TITLE
preview-tui with tmux and tmux-resurrect leaves empty panes when restoring a tmux session

### ISSUE THREAD

**Issue by Kabouik** [jarun/nnn#664]
`preview-tui` leaves an empty/unused pane when used with `tmux` and when restoring a previously saved `tmux` layout with `tmux-resurrect`).

Open `nnn` in `tmux` and load `preview-tui`:

```
   +---------------------------+
   |             |             |
   |             |             |
   |             |             |
   |     nnn     |   preview   |
   |             |             |
   |             |             |
   |             |             |
   +---------------------------+
```

Save the layout with `tmux-resurrect`, close, then reload the saved session:
```
   +---------------------------+
   |             |             |
   |     nnn     |             |
   |             |             |
   +-------------+     bash    |
   |             |             |
   |   preview   |             |
   |             |             |
   +---------------------------+
```

I suspect the new preview pane is opened just because I run `nnn` with `-P t` where `t` is my `preview-tui` keybind, else there would probably be just two panes when reloading the session, but the second pane would still be unused and calling `preview-tui` manually would open a new pane. 

@leovilok thinks this is due to `tmux-resurrect` checking which commands are running in each pane at save (`c-b` `c-s`) and then trying to respawn them when reloading (`c-b` `c-r`), and `NNN_FIFO` is missing when doing so. Since I posted that in the wrong place (#660), I wanted to continue the discussion here, but maybe there is no hope (in that case, sorry for the noise and the new-issue notification). However, isn't there a way to make sure `NNN_FIFO` exists when reloading? I launch `nnn` with the `-a` option so I would expect the file to exist if the `nnn` pane is respawned` before the preview pane (but maybe that is not the case).

**Comment by leovilok** [comment]
Once again, I don't use tmux too much, nor `tmux resurect`. But from the [docs](https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_programs.md), resoring programs is a tricky thing, that's why it's not enabled by default for every command. It seems that you modified your `tmux resurect` config already to add `nnn` to the whitelist, so you'll have to figure this out by yourself.

The [docs](https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_programs.md) seems pretty helpfull there, it tells you to check `~/.tmux/resurrect/last` to see what command are actually saved, to use stuff like `->` to specify command replacement, etc. Your goal might be to just avoid restoring the `preview-tui` window, as another one will be restored.

But this is, again, not a `nnn` issue, so you'll probably have to figure this out by yourself.

**Comment by Kabouik** [comment]
Thanks, I understand. I think the simplest will then be to close the preview manually before saving any session in `tmux-resurrect`, that should be enough. But it was worth asking if there would have been a way to force `NNN_FIFO` to exist or be restored at the same time.

**Comment by leovilok** [comment]
This is possible if you manage `NNN_FIFO` yourself, and not through `nnn -a`. But then you'll have to magane the FIFO file yourself, e.g. it won't be deleted by `nnn`. See the manual on `NNN_FIFO` if you are interested, but this is much more trouble than just using `-a`.
