### ISSUE TITLE
Show progress when processing long operations

### ISSUE THREAD

**Issue by ChefYeum** [jarun/nnn#718]
Show progress when processing long operations such as moving large files etc.

I'm currently moving some big bois on my laptop to OneDrive. 
The current version of nnn only shows:
![image](https://user-images.githubusercontent.com/36423861/91796228-9c32ad00-ec5a-11ea-9c0b-a79b68ccd9de.png)
(It's a cursor)

I have no idea how long it will take. Very tempted to C-c.

**Comment by jarun** [comment]
This is possible already. Please see https://github.com/jarun/nnn/issues/701.

**Comment by ChefYeum** [comment]
I was referring to something like this in Windows File Explorer:
![image](https://user-images.githubusercontent.com/36423861/91796758-f2ecb680-ec5b-11ea-8d05-d12f988d3ca2.png)

To know the progress rather than just a notification when complete.

**Comment by jarun** [comment]
See option `-r`. Also read https://github.com/jarun/nnn/wiki/Advanced-use-cases#cp-mv-progress

Please note that in order to use a powerful file manager like `nnn` you have to read the documentation. Unfortunately, we cannot spend time again and again on things those have already been implemented and documented.

**Comment by ChefYeum** [comment]
Thanks!
