### ISSUE TITLE
If `sshfs` is not installed, missing util is flashed for a second. More helpful error message is required.

### ISSUE THREAD

**Issue by thexavier666** [jarun/nnn#739]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: xubuntu 20.04
[x] Desktop Environment: i3
[x] Terminal Emulator: alacritty
[x] Shell: zsh
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[x] Issue exists on `nnn` master: v3.4

#### Exact steps to reproduce the issue

In a fresh install of xubuntu, sshfs is not installed. So the remote mount feature is not working.
Can a better error be shown, such as "Please install `sshfs` to mount remote directory", instead of "missing util"?

**Comment by jarun** [comment]
It's a common message for any missing deps. We do not want to mention what utility is missing because the workflows tell that (e.g. in this case sshfs) and it saves some bytes in the binary. When you see this, please visit the relevant Wiki section: https://github.com/jarun/nnn/wiki/Usage#dependencies

**Comment by jarun** [comment]
We have another issue on this now so I have added the patch to show the name of the utility.
