### ISSUE TITLE
Change selection mark position with detail mode

### ISSUE THREAD

**Issue by sylphenix** [jarun/nnn#741]
Is there an option to move the selection mark to the front of the entry name with detail mode? I think it is clearer which entry has been selected.
![nnn_ups](https://user-images.githubusercontent.com/59789740/94399124-64575080-0199-11eb-84a1-015e9b43988e.jpg)

**Comment by 0xACE** [comment]
I'm not sure it about moving the `+`.

Anyhow I'm not using master but this is my setup:

![select](https://user-images.githubusercontent.com/1482942/94449336-8356e200-019b-11eb-8a1a-d5e581d1d960.gif)


Didn't `master` adopt highlighting selected lines + add a blinking indicator if there are invisible selections?

**Comment by jarun** [comment]
The only thing I adopted was highlighting when selection part in status bar when something is selected.

How did you highlight the selected entries?

**Comment by 0xACE** [comment]
My code is heavily modified, hence large merge conflicts appear when I merge with `master`. Afaik I apply `A_REVERSE` to selected lines...

Atm my code is heavily scrambled as I have made 2 prototypes for drag and drop support, and am considering a 3rd one atm. In my experiments with drag and drop support, I think it may not be worth implementing it immediately to the terminal as it would only work on computers with a very specific patch-set, and lately I've been less and less on my own devices (Btw fun fact, yesterday: I encountered `nnn` in the wild for the first time. I clicked what I thought was a familiar looking `chess` icon in the start-menu, at first I thought I could play a game of chess game, but instead it launched in a terminal along with `nnn`, i was impressed, but then i got cucked because i never learned `master` keybindings, and I feel crippled without the `SEL_PAGER` luckily vim wasn't configured and loaded fast)... 

Geez, long rant, I'm trying to say: it maybe time for me to re-merge with `master` again and push some fixes to `master` soon. I'll see if I can push one obvious fix upstream later this week, just need to figure out detecting `glibc` versions and figure out what compilers utilize `__buildin_expect()`...
