### ISSUE TITLE
Option to temporarily increase navigation steps

### ISSUE THREAD

**Issue by sylphenix** [jarun/nnn#745]
**Is your feature request related to a problem? Please describe.**

It is a bit slow navigation with line-by-line, especially when the terminal has too many rows.

**Describe the solution you'd like**

I would like to add an option to specify the temporary navigation steps. With this option, when I holding down a modifier key (may be CTRL), and navigate with UP/DOWN key or mouse wheel, it could go by the specified steps.

**Comment by 0xACE** [comment]
Not sure that this will get added but, I'll contribute just in case.

The thing is: I find `nnn` configuration procedure unstructured and all over the place. Leading to the question: How would you suggest `nnn` reads these settings?

Another tip i have is `^D`and `^U` which jumps half a screen, but I'm not sure if it's my personal patch or if `master` has it, i know `master` atleast has `pageup` and `pagedown` bindings.

and finally, what do you think about a symbol indicating which line you can jump to:

![cap](https://user-images.githubusercontent.com/1482942/94554495-b192fb00-0249-11eb-9de9-26631897163e.png)

This screenshot reveals relative numbering allowing jumping to the exact file, i wasn't happy with it because of the collisions with switching tabs. Also I found that it only makes sense to have a single/static symbol for each character displayed on screen because it wouldn't require redrawing every line when moving around.

**Comment by jarun** [comment]
> Another tip i have is ^Dand ^U which jumps half a screen

That's correct. And PgUp and PgDn does full screen. I think that's the answer to the original question. We can't do more than that (a page full) anyway.

A better option could have been increasing the mouse repeat rate but I am not aware of any standard way to do that.

There are some solutions here which you can try out: https://unix.stackexchange.com/questions/58651/adjusting-keyboard-sensitivity-in-a-command-line-terminal

> I find nnn configuration procedure unstructured and all over the place.

We have everything in a single place in the Wiki: https://github.com/jarun/nnn/wiki/Usage#installation
If you think there's a better way - please go ahead.

For @sylphenix you can share the patch for numbering. Please share it here for future reference.

I am closing this defect though because we are not going to make nay code changes for this.
