### ISSUE TITLE
sourcing

### ISSUE THREAD

**Issue by sudo-ghost** [jarun/nnn#748]
#### Environment details (Put `x` in the checkbox along with the information)

[ ] Operating System: gentoo
[ ] Desktop Environment: bspwm
[ ] Terminal Emulator: alacritty
[ ] Shell: zsh
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[ ] Issue exists on `nnn` master

so idk if this is a bug or its a me problem but for some reason the plugins will not work unless i run source ~/.zshrc every single terminal session. i dont know if this is just how its suppose to be or if there is a way to automate it or if its something with my zshrc. ive tried looking up things but ive come up dry so im posting here

**Comment by 0xACE** [comment]
There are for too few details here so I'll just make a wild guess:

Chances are your `NNN_PLUG` environment variable is within `~/.zshrc`, therefore you need to ensure that `~/.zshrc` is sourced to gain access to the settings your have defined in `~/.zshrc`.

My guess is your `zsh` environment is setup incorrectly so that `~/.zshrc` isn't lading in this case. I don't have `zsh` so I can't help further, but in `bash` I think the real `rc` file is `~/.bash_profile`

**Comment by sudo-ghost** [comment]
maybe it needs to be in zprofile? ill try that and report back

**Comment by jarun** [comment]
What is the output of `echo $SHELL`?

**Comment by sudo-ghost** [comment]
/bin/zsh

**Comment by jarun** [comment]
I guess the problem may be .zshrc is not loaded when zsh starts. I see some discussion here: https://stackoverflow.com/questions/49887469/why-wont-zshrc-load

Anyway, it's a local issue why your .zshrc is not loading when zsh starts. It's extremely difficult to solve local environment problems remotely. Please debug yourself.

**Comment by sudo-ghost** [comment]
also since i just tried it sourcing it in zprofile does not fix the issue

**Comment by 0xACE** [comment]
@sudo-ghost if `env | grep "NNN_"` doesn't  yield results, `nnn` won't be able to do anything i have `[[ -f ~/.bashrc ]] && . ~/.bashrc` in my `.bash_profile`
