### ISSUE TITLE
nnn opens everything with firefox browser, disrespecting the xdg-mime default settings.

### ISSUE THREAD

**Issue by OrkeshNurbolat** [jarun/nnn#760]
[x] Operating System: Arch Linux
[x] Desktop Environment: dwm
[x] Terminal Emulator:st
[x] Shell:zsh
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Alright , it is like this 
I had set up the xdg-open correctly since in the zsh or bash promt
when I type:
  xdg-open Makefile , it opens with vim

but in nnn, I come to the same file and open.
the nnn just become slow as a sloth, and a while after there pops out the firefox that opens that Makefile

so it doesn't work even if the xdg-open works correctly.

**Comment by jarun** [comment]
Please make an effort to find and read the documentation before an issue on a project: https://github.com/jarun/nnn/wiki/Troubleshooting#wrong-file-opener

**Comment by jarun** [comment]
And also read this from the front page: https://github.com/jarun/nnn#quickstart

Text files are covered.

**Comment by jarun** [comment]
Did you follow the steps in the 2 second point in Quickstart to open text files in VISUAL/EDITOR? The option `-e`.
Do you still see the problem?

It's very very difficult to troubleshoot local issues. nnn is going to be 3 with 1000s of users. We are past that stage and I don't see the problem that you see because distros differ, env settings differ. Even xdg-open has different wrappers on different distros. Do you know that xdg-open behaves differently in purely cli environment and a terminal in a desktop?

You mentioned 8k of code. Did you see that without the `-e` option we just call xdg-open? https://github.com/jarun/nnn/blob/dbf12ed031cb26394ca1c8a0b0dcf3ad1a2b523b/src/nnn.c#L6221

You mentioned `xdg-open Makefile , it opens with vim`, is it gvim or vim in the terminal? But anyway, it's really difficult to determine what xdg-open follows. So just use the option `-e`, set VISUAL/EDITOR and get it over with.

**Comment by OrkeshNurbolat** [comment]
Thanks very much for patience , "xdg-mime" are complicated to setup. I think I directly edit their files cause them to mess up somewhere. or a bad flag passed in the spawn.

I wrote myself a  costume opener and  all worked well (nuke is kinda too comprehensive ). 
hated the mimes anyway.

the "-e" option opens every text file  with one and only $EDITOR .
the "-c" option does its job well, since the cli flag solved all my problem.

the spawner sometimes become laggie when open with xdg, if it wasn't mentioned
I think it is still a bad gui flag causing these.

kinda laughed when the 300th  issue deleted , peace bro .
