### ISSUE TITLE
Dynamic X window title in nnn?

### ISSUE THREAD

**Issue by nathanielevan** [jarun/nnn#769]
Hi, first of all thank you so much for nnn, it is now my go-to file manager on Linux and has been for several months now, loving it.

**Describe the solution you'd like**

I would like it if nnn could display an X window title that shows the current directory, and changes dynamically when I move between directories. Something like, say, `nnn: ~/Documents/project-1/bin`. (For comparison, ranger can do this by setting `set update_title true` in rc.conf, see image below.) Otherwise, it's not a dealbreaker, but I simply thought it would be nice to have it.

**Describe alternatives you've considered**

I use zsh, and configured it to display the currently running program in the window title. It can't, however, dynamically change the window title when I'm changing directories in nnn, and I think this has to be implemented in nnn itself, and I'm not very familiar with C.

**Additional context**

![2020-10-30-224201](https://user-images.githubusercontent.com/9361126/97725925-4d41b080-1b01-11eb-9466-8ddaccca87a7.png)

Looking forward to your reply!

**Comment by jarun** [comment]
I can understand this may be good to have if you having only 1 context. However, `nnn` has 4 (can have up to 8 compiled-in) contexts where you can browse different directories. So showing only 1 is not even technically correct.

In addition I would also like to avoid good-to-have configs and extra processing given the current feature completeness of the project.

**Comment by nathanielevan** [comment]
Ah, well, regarding the context, you can also display the current context along with the directory the context is in, like `nnn: ~/Documents/project/bin [1]`, so that way I think it can be a bit more informative and useful. Now that you say it, ranger also has a feature called "tabs" (similar to nnn's contexts), but it also only displays the current tab you're in, in the window title.

That being said, I completely understand you having other priorities for nnn.

**Comment by jarun** [comment]
> I completely understand you having other priorities for nnn.

Thanks for your understanding.

It becomes a problem for us if users request each and every minor feature they see in other file managers.

I would suggest you request the other file manager to add the features you like in `nnn`. That way you don't have to switch. Every file manager has its own plus points and I don't think it's a bad thing to have choices. For example, in this case, as I understand, if we have to support what you are looking for, we need to pass some details to X in some way every time we switch a directory in `nnn`. I am not up for that additional processing. People who pick `nnn` like it because of its performance. A lot of it comes from not doing redundant stuff.
