### ISSUE TITLE
Why "unorthodoxe" file manager ?

### ISSUE THREAD

**Issue by sucrecacao** [jarun/nnn#772]
In my opinion it is the most orthodox file manager as it does one thing and do it well.

**Comment by jarun** [comment]
If we go by the book - "Orthodox file managers are file managers that follow a two-panel paradigm, and are heavily influenced by Norton Commander."

`nnn` will never be 2-pane (by itself) or anything like norton commander. Hence the tagline.

And the other way to look at it is - `nnn` has been disruptive because of the type of features it delivers and design principles. It's nothing like any other file manager that exists.
