### ISSUE TITLE
Vim-style keybindings for moving around

### ISSUE THREAD

**Issue by nsirolli** [jarun/nnn#827]
It would be nice to be able to move around the files using vim-style keybindings: for example, type `7j` to move down seven lines. Or am I intended to achieve this in some other way?

**Comment by 0xACE** [comment]
It has been requested multiple times and denied.

From my experimentation I noticed that `<count>j` wouldn't work well because the numbered keys are reserved for switching contexts...

I also considered "jump"-labels where you head a `<leader>` key and then the file you want to reach... It was all messy.

Have you tried `'t` to jump to the first file starting on the letter `t` or `''` to jump to the first file?

**Comment by nsirolli** [comment]
Yes, I noticed that it would not be compatible with the use of numbers for switching contexts; probably changing that would not be desirable for many users. But it could be, if not the default behaviour, at least an option / plugin.

Anyway, thanks for the `'t` advice!

**Comment by jarun** [comment]
Closing the issue.
