### ISSUE TITLE
Make NNN_TMPFILE as option to where actually write lastd file

### ISSUE THREAD

**Issue by z0rc** [jarun/nnn#859]
**Is your feature request related to a problem? Please describe.**

According to source `NNN_TMPFILE` env var is used only as feature flag whether to write lastd file or not. But the way `quitcd` script is made suggests that `NNN_TMPFILE` actually affects where it can be placed. I'd like to do something like `export NNN_TMPFILE=${TMPDIR:-/tmp}/nnn-${USER}/lastd.$$`, so multiple nnn instances from multiple terminal tabs won't fight for single lastd file.

**Describe the solution you'd like**

Make `NNN_TMPFILE` as option to where lastd file is written.

**Comment by jarun** [comment]
> so multiple nnn instances from multiple terminal tabs won't fight for single lastd file

I don't think that's a problem because it's instantaneous and a user can only exit from one terminal at a time.

As far as I remember, it was like that earlier. But removing the dependency means 1 less variable to read at start-up. Currently it is read only when the user exits. In fact, you don't even need to define `NNN_TMPFILE` if the default behaviour to land in the same dir where you started on pressing `q` is OK with you.
