### ISSUE TITLE
How can I open multiple files in MPV as a playlist?

### ISSUE THREAD

**Issue by David-Else** [jarun/nnn#866]
How can I open multiple files using `nnn` in MPV (my default player) so they play one after another? If I use the terminal:
```
mpv file1 file2 file3
```
They open in a playlist, and it also works out of the box in Ranger FM. 

Let us say I use `space` or `a` to select multiple `.mkv` video files, I want them to open in MPV in a playlist.

In `nnn` I only get one file playing with no playlist however many files I have selected.

Thanks!

**Comment by jarun** [comment]
Please take a look at the plugin `mocplay` which adds multiple files for mocp. You can add a similar logic in `nuke` which is a custom opener. The other way would be to just modify `mocplay` to invoke mpv.

**Comment by jarun** [comment]
Note that `nnn` opens the current file on `Enter`. So you need to use the selection in the plugin to work on all the selected files together.

**Comment by David-Else** [comment]
This seems very complex for a simple operation, maybe I am not asking the question very well. 

> Note that nnn opens the current file on Enter

What command do I use to open the _selection_ of files, not the current file?

I just want `nnn` to open a selection of files into `mpv`, just like if I use the terminal `mpv file1 file2 file3`. Do I have to modify an extension to do this?

I am looking at `nuke`, and assume this is the conditional clause I need to target:
```
handle_video() {
...
    elif [ "$GUI" -ne 0 ] && which mpv >/dev/null 2>&1; then
        nohup mpv "${FPATH}" >/dev/null 2>&1 &
        exit 0
...
}
```
How can `"${FPATH}"` be the list of files I selected?

How do most people add playlists of videos or music to players in `nnn`? Thanks!

**Comment by KlzXS** [comment]
I'd say the easiest might be to make a plugin that plays the whole selection in `mpv`. See existing plugins to see how they access the selection.

> How do most people add playlists of videos or music to players in nnn? 

Personally I don't and I don't recall anybody mentioning this already.

**Comment by 0xACE** [comment]
> How do most people add playlists of videos or music to players in `nnn`? Thanks!

I just used this:
```
curl -L https://github.com/mpv-player/mpv/raw/master/TOOLS/umpv |  sed 's/ append/ replace/'
```
This allows you to just hit enter and mpv will open the file in the running instance of `umpv`

Though you could keep `append` if you like to queue items instead...

**Comment by jarun** [comment]
> This seems very complex for a simple operation, maybe I am not asking the question very well.

Not really if you check the example `mocplay` plugin and the relevant code:

```
selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
...
xargs < "$selection" -0 mocp -a
```

**Comment by jarun** [comment]
BTW, @David-Else just because a tool does it on-the-fly on _Enter_ doesn't mean it is the right behaviour. See the below use cases.

1. Let's say the user is in the process of selecting some files. The names don't indicate anything. So he has to listen and select. So does she need to open all the files each time she wants to listen to one?
2. What happens when there are some text and audio files in the selection and the user is planning to move them? If the user opens a text file does it open all text files in the text editor and the audio files in the audio player? If it does, it's more of an annoyance than user experience improvement. If it doesn't (multi open happens only for a bunch of multimedia players), it's a hack. Your tool is actually parsing your data _unnecessarily_ everytime you select multiple files to make extension/mime checks.
3. Not every audio player supports queuing the same way - it may not support, it may take additional flags... so the effort to make it work for every audio player on all user environments is futile.

So no, `nnn` doesn't try to guess your environment and use-cases and per-decide workflows. It tries to remain generic with sane examples (in the form of plugins) to extend the functionality.

**Comment by David-Else** [comment]
Thanks everyone for helping me out on this, I only found `nnn` yesterday and am just discovering how it is designed around plugins to extend the functionality.

@jarun I appreciate the design decision is a good one, I was expecting it to work like Ranger FM and just hoping it would.

A really nice plugin might be called `add to playlist`:

- It only runs if the user has selected multiple files of the same type
- It then determines which player the user has for that file type and checks on a white list it can accept the `player file1 file2 file3` format and then adds them to the playlist

If I ever get the time I might try and write it, but unfortunately, it won't be any time soon.

Anyway, amazing software, Ranger FM is now thrown in the 'bloat bin' :)

**Comment by jarun** [comment]
> If I ever get the time I might try and write it, but unfortunately, it won't be any time soon.

No problem! Just follow the other case in `mocplay` which checks the extension as well.

**Comment by 0xACE** [comment]
If you want to use `umpv` just do something like this:
```sh
mkdir -p ~/bin
export PATH=$PATH:~/bin
curl -L https://github.com/mpv-player/mpv/raw/master/TOOLS/umpv > ~/bin/umpv
cat << EOF > "$HOME/.config/nnn/plugins/addtoplaylist"
#!/usr/bin/env sh
player="umpv"
selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
if [ -s "$selection" ]; then
  xargs -0 "$player" < "$selection"
else
  "$player" "$1"
fi
EOF
chmod +x "$HOME/.config/nnn/plugins/addtoplaylist"
export NNN_PLUG="$NNN_PLUG;p:addtoplaylist"
```

Without `umpv` you'd  have to convert the `\0` selection list into a command line argument for your `player` of choice.

**Comment by David-Else** [comment]
@0xACE Brilliant, it works! Cheers :)

**Comment by jarun** [comment]
@0xACE your solution is really useful! It also takes care of queuing from from multiple instances. :+1:

**Comment by jarun** [comment]
Probably just add a plugin for this so people have it handy.
