### ISSUE TITLE
How to change the default editor?

### ISSUE THREAD

**Issue by andrew-manger** [jarun/nnn#874]
When I press 'e' on a file in nnn, it opens in vim. How can I change it so it opens in nano?

**Comment by jarun** [comment]
You have to change the environment variable `VISUAL` or `EDITOR`.

Please read the program help and documentation.

**Comment by andrew-manger** [comment]
That's not very helpful. What environment variable and where? The docs don't specify any of this. I'm not as familiar as others are. Can you explain exactly what I need to do and what file I have to edit?

**Comment by KlzXS** [comment]
The environment variables of the shell by editing the shell's configuartion file. For bash it's `~/.bashrc`. Add `export EDITOR="nano"`.

This is basic shell configuration. `nnn`, as well as many other programs, reads the environment variables to determine what to do. Since this is not specific to `nnn` there is no need to explicitly document any of it.
