### ISSUE TITLE
no version information available (required by nnn)

### ISSUE THREAD

**Issue by rubic** [jarun/nnn#9]
I'm getting the following warning messages:

```
nnn: /lib/x86_64-linux-gnu/libncurses.so.5: no version information available (required by nnn)
nnn: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by nnn)
```

Installed from the Ubuntu PPA

Environment:

3.13.0-115-generic #162-Ubuntu SMP Fri Mar 24 16:03:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shaggytwodope** [comment]
@rubic what ubuntu version?

**Comment by rubic** [comment]
Ubuntu 14.04.5 LTS

**Comment by shaggytwodope** [comment]
@rubic The packages are being rebuilt for each ubuntu version as I type this. It may take a few moments to be available. Please update normally and confirm it is working.

**Comment by rubic** [comment]
Confirmed issue fixed with the last update.  Thanks.

**Comment by shaggytwodope** [comment]
@jarun This issue came from me not building the packages for ALL series. I overlooked this possibility greatly. I've now and will continue to do unique builds for each on going ubuntu series. It may be of note to you the versioning for the package will be named with the series. For example `nnn - 1.0-3~trusty`. Worth noting for any possible bug reports or issues made.

**Comment by jarun** [comment]
Thanks for the information @shaggytwodope! We are good!
