### ISSUE TITLE
Selection marker dissapears and cpmvas copying files to themselves

### ISSUE THREAD

**Issue by dymn** [jarun/nnn#958]
Gentoo x86-64, nnn-4.0

1.The "+" sign for file selections disappears when changing the context and returning back, but the selection itself is meant, as indicated by the number in the status bar. It can be very dangerous.

2. If I have a file named ‘a.txt’ and I want to make a copy of it named ‘b.txt’ in the same directory, I do the following: I select ‘a.txt’ so that it has a + prefixed to it’s name, press ‘w’ and then press ‘c’ to copy (as). However, after pressing ‘c’, instead of being asked to input a new name (‘b.txt’) my text editor gvim is launched and I get a cp error message in nnn’s terminal stating that "‘a.txt’ can’t be copied to ‘a.txt’". How to copy the file to the same directory with another name?

**Comment by KlzXS** [comment]
1. This is intentional. Selection markers are clear on directory/context change. There isn't a way to keep them across directories that's both easy and low in resource usage. So that's that.

2. I haven't tested this myself, but I trust the finding fully. It would have to do with `gvim` being a graphical program, as such `nnn` doesn't wait for it to exit which in turn means that the temporary file is used unchanged and files are copied to themselves.

An easy fix would be to use `vim` or another terminal editor. I'll keep this open for now in case anyone wants to chime in, but feel free to close the issue if you are satisfied with the fix.

**Comment by dymn** [comment]
Thanks for the quick response.
1. Is it possible to highlight the status of the selection in the status bar, and the "+" signs themselves next to the files, in some bright color so that they draw attention to themselves?
2. gvim in my case is an attempt to get away from a locked terminal with nnn while editing a file. Same behavior with ewrap and the xfce4-terminal -e "vim \" $ * \ "" command in it.

**Comment by jarun** [comment]
1. Yes, it's very easy now. Use any color and attribute you like around the following line:

https://github.com/jarun/nnn/blob/a629707eecc6ffc1023b93670400830554676487/src/nnn.c#L3670

2. Please read the following section, specially the note that starts with IMPORTANT:

https://github.com/jarun/nnn/wiki/Basic-use-cases#detached-text

> How to copy the file to the same directory with another name?

For individual files: https://github.com/jarun/nnn/wiki/Basic-use-cases#duplicate-file

**Comment by jarun** [comment]
Settled with reverse. Try commit 7acc9196d5d7ce98446d23531ccf2a171ded7187.
